@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "publicNetworkAccess": true,
  "encryption": {
    "keySource": "Microsoft.Automation",
    "identity": {
      "userAssignedIdentity": null
    }
  },
  "privateEndpointConnections": [],
  "state": "Ok",
  "creationTime": "2025-04-08T11:38:15.2966667Z",
  "sku": {
    "name": "Basic",
    "capacity": null,
    "family": null
  },
  "disableLocalAuth": false,
  "lastModifiedTime": "2025-04-08T11:38:15.2966667Z",
  "lastModifiedBy": null,
  "automationHybridServiceUrl": "https://3d7179e6-c0b2-45cd-b50e-4c761730fde1.jrds.noe.azure-automation.net/automationAccounts/3d7179e6-c0b2-45cd-b50e-4c761730fde1",
  "RuntimeConfiguration": {
    "powershell72": {
      "builtinModules": {
        "Az": "11.2.0"
      }
    },
    "powershell7": {
      "builtinModules": {
        "Az": "8.0.0"
      }
    },
    "powershell": {
      "builtinModules": {
        "Az": "11.2.0"
      }
    }
  },
  "RegistrationUrl": "https://3d7179e6-c0b2-45cd-b50e-4c761730fde1.agentsvc.noe.azure-automation.net/accounts/3d7179e6-c0b2-45cd-b50e-4c761730fde1"
}
}
@enduml
