@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "enabled": true,
  "actions": [
    {
      "actionType": "AddActionGroups",
      "actionGroupIds": [
        "/subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/resourceGroups/lz-norwayeast/providers/Microsoft.Insights/actionGroups/lz-sre-ag"
      ]
    }
  ],
  "scopes": [
    "/subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/resourceGroups/lz-norwayeast/providers/Microsoft.RecoveryServices/vaults/lz-norwayeast-rsv"
  ],
  "conditions": [
    {
      "operator": "Equals",
      "field": "MonitorCondition",
      "values": [
        "Fired"
      ]
    }
  ]
}
}
@enduml
