@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "enabled": true,
  "actions": [
    {
      "actionType": "AddActionGroups",
      "actionGroupIds": [
        "/subscriptions/0/resourceGroups/lz-norwayeast/providers/Microsoft.Insights/actionGroups/lz-sre-ag"
      ]
    }
  ],
  "scopes": [
    "/subscriptions/0/resourceGroups/lz-norwayeast/providers/Microsoft.RecoveryServices/vaults/lz-norwayeast-rsv"
  ],
  "conditions": [
    {
      "operator": "Equals",
      "values": [
        "Fired"
      ],
      "field": "MonitorCondition"
    }
  ]
}
}
@enduml
