@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "enabled": true,
  "actions": {
    "actionGroups": [
      {
        "actionGroupId": "/subscriptions/0/resourceGroups/lz-norwayeast/providers/Microsoft.Insights/actionGroups/lz-sec-ag"
      }
    ]
  },
  "condition": {
    "allOf": [
      {
        "equals": "Administrative",
        "field": "category"
      },
      {
        "equals": "Microsoft.Sql/servers/firewallRules/write",
        "field": "operationName"
      },
      {
        "field": "level",
        "containsAny": [
          "Critical",
          "Error",
          "Warning",
          "Informational"
        ]
      }
    ]
  },
  "scopes": [
    "/subscriptions/0"
  ]
}
}
@enduml
