@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "enabled": true,
  "automationRunbookReceivers": [],
  "azureFunctionReceivers": [],
  "azureAppPushReceivers": [],
  "logicAppReceivers": [],
  "eventHubReceivers": [
    {
      "name": "security advisories",
      "tenantId": "0",
      "useCommonAlertSchema": true,
      "subscriptionId": "c117acbf-d744-4c7f-a748-a9408b250ac3",
      "eventHubNameSpace": "p-servicehealth-evhns",
      "eventHubName": "p-securityadvisories-evh"
    }
  ],
  "webhookReceivers": [],
  "armRoleReceivers": [],
  "emailReceivers": [],
  "groupShortName": "SRE Teams",
  "voiceReceivers": [],
  "itsmReceivers": [],
  "smsReceivers": []
}
}
@enduml
