@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "enabled": true,
  "automationRunbookReceivers": [],
  "azureFunctionReceivers": [],
  "azureAppPushReceivers": [],
  "logicAppReceivers": [],
  "eventHubReceivers": [
    {
      "name": "health advisories",
      "tenantId": "67508d80-2b69-484e-ab62-ab263ca94733",
      "useCommonAlertSchema": true,
      "subscriptionId": "c117acbf-d744-4c7f-a748-a9408b250ac3",
      "eventHubNameSpace": "p-servicehealth-evhns",
      "eventHubName": "p-healthadvisories-evh"
    }
  ],
  "webhookReceivers": [],
  "armRoleReceivers": [],
  "groupShortName": "SRE Teams",
  "emailReceivers": [],
  "voiceReceivers": [],
  "itsmReceivers": [],
  "smsReceivers": []
}
}
@enduml
