@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties [
  {
    "provisioningState": "Succeeded",
    "type": "ConfigurationforWindows",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "1.0",
    "publisher": "Microsoft.GuestConfiguration"
  },
  {
    "provisioningState": "Succeeded",
    "type": "ConfigurationforWindows",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "1.0",
    "publisher": "Microsoft.GuestConfiguration"
  },
  {
    "provisioningState": "Succeeded",
    "type": "ConfigurationforWindows",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "1.0",
    "publisher": "Microsoft.GuestConfiguration"
  }
]
}
@enduml
