@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties [
  {
    "provisioningState": "Succeeded",
    "type": "AzureMonitorWindowsAgent",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "1.0",
    "enableAutomaticUpgrade": true,
    "publisher": "Microsoft.Azure.Monitor"
  },
  {
    "provisioningState": "Succeeded",
    "type": "AzureMonitorWindowsAgent",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "1.0",
    "enableAutomaticUpgrade": true,
    "publisher": "Microsoft.Azure.Monitor"
  },
  {
    "provisioningState": "Succeeded",
    "type": "AzureMonitorWindowsAgent",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "1.0",
    "publisher": "Microsoft.Azure.Monitor"
  },
  {
    "provisioningState": "Succeeded",
    "type": "AzureMonitorWindowsAgent",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "1.0",
    "enableAutomaticUpgrade": true,
    "publisher": "Microsoft.Azure.Monitor"
  }
]
}
@enduml
