@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "type": "CustomScriptExtension",
  "autoUpgradeMinorVersion": true,
  "typeHandlerVersion": "1.9",
  "publisher": "Microsoft.Compute",
  "settings": {}
}
}
@enduml
