@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "platformFaultDomainCount": 2,
  "virtualMachineScaleSetMigrationInfo": {
    "defaultVirtualMachineScaleSetInfo": {
      "constrainedMaximumCapacity": true,
      "defaultVirtualMachineScaleSet": {
        "id": "/subscriptions/0/resourceGroups/rg-aleksander/providers/Microsoft.Compute/virtualMachineScaleSets/d-awh-wm-avail"
      }
    }
  },
  "platformUpdateDomainCount": 5,
  "virtualMachines": [
    {
      "id": "/subscriptions/0/resourceGroups/RG-ALEKSANDER/providers/Microsoft.Compute/virtualMachines/D-AWH-WM1"
    }
  ]
}
}
@enduml
