@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "publicNetworkAccess": "Enabled",
  "tenantId": "67508d80-2b69-484e-ab62-ab263ca94733",
  "enabledForTemplateDeployment": true,
  "sku": {
    "name": "standard",
    "family": "A"
  },
  "enabledForDeployment": true,
  "softDeleteRetentionInDays": 90,
  "enabledForDiskEncryption": true,
  "enableSoftDelete": true,
  "accessPolicies": [],
  "enableRbacAuthorization": true,
  "enablePurgeProtection": true,
  "vaultUri": "https://d-awhsandbox-kv.vault.azure.net/"
}
}
@enduml
