@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "encryption": {
    "keySource": "Microsoft.Storage",
    "services": {
      "blob": {
        "enabled": true,
        "lastEnabledTime": "2025-05-21T09:51:33.34107Z",
        "keyType": "Account"
      },
      "file": {
        "enabled": true,
        "lastEnabledTime": "2025-05-21T09:51:33.34107Z",
        "keyType": "Account"
      }
    }
  },
  "privateEndpointConnections": [],
  "supportsHttpsTrafficOnly": true,
  "allowBlobPublicAccess": false,
  "minimumTlsVersion": "TLS1_2",
  "allowCrossTenantReplication": false,
  "primaryEndpoints": {
    "blob": "https://dawhwmdiagsett3f.blob.core.windows.net/",
    "file": "https://dawhwmdiagsett3f.file.core.windows.net/",
    "table": "https://dawhwmdiagsett3f.table.core.windows.net/",
    "queue": "https://dawhwmdiagsett3f.queue.core.windows.net/",
    "web": "https://dawhwmdiagsett3f.z1.web.core.windows.net/",
    "dfs": "https://dawhwmdiagsett3f.dfs.core.windows.net/"
  },
  "keyCreationTime": {
    "key2": "2025-05-21T09:51:33.34107Z",
    "key1": "2025-05-21T09:51:33.34107Z"
  },
  "primaryLocation": "norwayeast",
  "statusOfPrimary": "available",
  "creationTime": "2025-05-21T09:51:33.278573Z",
  "networkAcls": {
    "virtualNetworkRules": [
      {
        "id": "/subscriptions/0/resourceGroups/lz-network-norwayeast/providers/Microsoft.Network/virtualNetworks/lz-network-norwayeast-vnet/subnets/default",
        "state": "Succeeded",
        "action": "Allow"
      }
    ],
    "defaultAction": "Deny",
    "ipv6Rules": [],
    "ipRules": [],
    "bypass": "AzureServices"
  },
  "accessTier": "Hot",
  "largeFileSharesState": "Enabled"
}
}
@enduml
