@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "2": {
    "provisioningState": "Succeeded",
    "type": "NetworkWatcherAgentWindows",
    "typeHandlerVersion": "1.4",
    "autoUpgradeMinorVersion": true,
    "publisher": "Microsoft.Azure.NetworkWatcher"
  },
  "1": {
    "provisioningState": "Succeeded",
    "type": "NetworkWatcherAgentWindows",
    "typeHandlerVersion": "1.4",
    "autoUpgradeMinorVersion": true,
    "publisher": "Microsoft.Azure.NetworkWatcher"
  },
  "4": {
    "provisioningState": "Succeeded",
    "type": "NetworkWatcherAgentWindows",
    "typeHandlerVersion": "1.4",
    "autoUpgradeMinorVersion": true,
    "publisher": "Microsoft.Azure.NetworkWatcher"
  },
  "0": {
    "provisioningState": "Succeeded",
    "type": "NetworkWatcherAgentWindows",
    "typeHandlerVersion": "1.4",
    "autoUpgradeMinorVersion": true,
    "publisher": "Microsoft.Azure.NetworkWatcher"
  },
  "3": {
    "provisioningState": "Succeeded",
    "type": "NetworkWatcherAgentWindows",
    "typeHandlerVersion": "1.4",
    "autoUpgradeMinorVersion": true,
    "publisher": "Microsoft.Azure.NetworkWatcher"
  }
}
}
@enduml
