@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "source": {
    "id": "/subscriptions/0/resourceGroups/rg-audun/providers/Microsoft.Compute/virtualMachines/linux-backup-test",
    "location": "NorwayEast"
  },
  "restorePointCollectionId": "676b44e4-83e1-40fc-b20a-22a81f5c448a"
}
}
@enduml
