@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "0": {
    "provisioningState": "Succeeded",
    "resourceGuid": "1aa5a1b6-92e0-4d22-8d76-a5eaca4919fd",
    "privateEndpointVNetPolicies": "Disabled",
    "virtualNetworkPeerings": [],
    "enableDdosProtection": false,
    "subnets": [
      {
        "properties": {
          "provisioningState": "Succeeded",
          "ipConfigurations": [
            {
              "id": "/subscriptions/0/resourceGroups/RG-AUDUN/providers/Microsoft.Network/networkInterfaces/LINUX-BACKUP-TESTVMNIC/ipConfigurations/IPCONFIGLINUX-BACKUP-TEST"
            }
          ],
          "privateLinkServiceNetworkPolicies": "Enabled",
          "privateEndpointNetworkPolicies": "Disabled",
          "addressPrefix": "10.0.0.0/24",
          "delegations": []
        },
        "name": "default",
        "type": "Microsoft.Network/virtualNetworks/subnets",
        "id": "/subscriptions/0/resourceGroups/rg-audun/providers/Microsoft.Network/virtualNetworks/lz-network-norwayeast-vnet/subnets/default",
        "etag": "W/\"15194983-ad8d-4d31-8114-10bf55a130f6\""
      }
    ],
    "addressSpace": {
      "addressPrefixes": [
        "10.0.0.0/16"
      ]
    }
  },
  "1": {
    "provisioningState": "Succeeded",
    "resourceGuid": "1aa5a1b6-92e0-4d22-8d76-a5eaca4919fd",
    "privateEndpointVNetPolicies": "Disabled",
    "virtualNetworkPeerings": [],
    "enableDdosProtection": false,
    "subnets": [
      {
        "properties": {
          "provisioningState": "Succeeded",
          "ipConfigurations": [
            {
              "id": "/subscriptions/0/resourceGroups/RG-AUDUN/providers/Microsoft.Network/networkInterfaces/LINUX-BACKUP-TESTVMNIC/ipConfigurations/IPCONFIGLINUX-BACKUP-TEST"
            }
          ],
          "privateLinkServiceNetworkPolicies": "Enabled",
          "privateEndpointNetworkPolicies": "Disabled",
          "addressPrefix": "10.0.0.0/24",
          "delegations": []
        },
        "name": "default",
        "type": "Microsoft.Network/virtualNetworks/subnets",
        "id": "/subscriptions/0/resourceGroups/rg-audun/providers/Microsoft.Network/virtualNetworks/lz-network-norwayeast-vnet/subnets/default",
        "etag": "W/\"15194983-ad8d-4d31-8114-10bf55a130f6\""
      }
    ],
    "addressSpace": {
      "addressPrefixes": [
        "10.0.0.0/16"
      ]
    }
  }
}
}
@enduml
