@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "3": {
    "provisioningState": "Succeeded",
    "type": "MDE.Linux",
    "typeHandlerVersion": "1.0",
    "autoUpgradeMinorVersion": true,
    "publisher": "Microsoft.Azure.AzureDefenderForServers",
    "settings": {
      "forceReOnboarding": false,
      "azureResourceId": "/subscriptions/0/resourceGroups/RBAC-TEST/providers/Microsoft.Compute/virtualMachines/t-linux-vm",
      "vNextEnabled": false,
      "autoUpdate": true
    },
    "forceUpdateTag": "c37c3df3-2e5c-4f47-8532-b4c7d2c59522"
  },
  "0": {
    "provisioningState": "Succeeded",
    "type": "MDE.Linux",
    "typeHandlerVersion": "1.0",
    "autoUpgradeMinorVersion": true,
    "publisher": "Microsoft.Azure.AzureDefenderForServers",
    "settings": {
      "forceReOnboarding": false,
      "azureResourceId": "/subscriptions/0/resourceGroups/RBAC-TEST/providers/Microsoft.Compute/virtualMachines/t-linux-vm",
      "vNextEnabled": false,
      "autoUpdate": true
    },
    "forceUpdateTag": "c37c3df3-2e5c-4f47-8532-b4c7d2c59522"
  },
  "1": {
    "provisioningState": "Succeeded",
    "type": "MDE.Linux",
    "typeHandlerVersion": "1.0",
    "autoUpgradeMinorVersion": true,
    "publisher": "Microsoft.Azure.AzureDefenderForServers",
    "settings": {
      "forceReOnboarding": false,
      "azureResourceId": "/subscriptions/0/resourceGroups/RBAC-TEST/providers/Microsoft.Compute/virtualMachines/t-linux-vm",
      "vNextEnabled": false,
      "autoUpdate": true
    },
    "forceUpdateTag": "c37c3df3-2e5c-4f47-8532-b4c7d2c59522"
  },
  "2": {
    "provisioningState": "Succeeded",
    "type": "MDE.Linux",
    "typeHandlerVersion": "1.0",
    "autoUpgradeMinorVersion": true,
    "publisher": "Microsoft.Azure.AzureDefenderForServers",
    "settings": {
      "forceReOnboarding": false,
      "azureResourceId": "/subscriptions/0/resourceGroups/RBAC-TEST/providers/Microsoft.Compute/virtualMachines/t-linux-vm",
      "vNextEnabled": false,
      "autoUpdate": true
    },
    "forceUpdateTag": "c37c3df3-2e5c-4f47-8532-b4c7d2c59522"
  }
}
}
@enduml
