@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "publicNetworkAccess": "Enabled",
  "encryption": {
    "requireInfrastructureEncryption": false,
    "keySource": "Microsoft.Storage",
    "services": {
      "blob": {
        "enabled": true,
        "lastEnabledTime": "2024-11-27T13:03:27.3025065Z",
        "keyType": "Account"
      },
      "file": {
        "enabled": true,
        "lastEnabledTime": "2024-11-27T13:03:27.3025065Z",
        "keyType": "Account"
      }
    }
  },
  "privateEndpointConnections": [],
  "supportsHttpsTrafficOnly": true,
  "allowBlobPublicAccess": false,
  "minimumTlsVersion": "TLS1_2",
  "allowCrossTenantReplication": false,
  "primaryEndpoints": {
    "blob": "https://sweethomealabamaandback.blob.core.windows.net/",
    "file": "https://sweethomealabamaandback.file.core.windows.net/",
    "table": "https://sweethomealabamaandback.table.core.windows.net/",
    "queue": "https://sweethomealabamaandback.queue.core.windows.net/",
    "web": "https://sweethomealabamaandback.z1.web.core.windows.net/",
    "dfs": "https://sweethomealabamaandback.dfs.core.windows.net/"
  },
  "statusOfPrimary": "available",
  "keyCreationTime": {
    "key2": "2024-11-27T13:03:26.9587902Z",
    "key1": "2024-11-27T13:03:26.9587902Z"
  },
  "primaryLocation": "norwayeast",
  "creationTime": "2024-11-27T13:03:26.8961819Z",
  "allowSharedKeyAccess": true,
  "networkAcls": {
    "virtualNetworkRules": [],
    "defaultAction": "Allow",
    "ipv6Rules": [],
    "ipRules": [],
    "bypass": "AzureServices"
  },
  "defaultToOAuthAuthentication": false,
  "accessTier": "Hot",
  "largeFileSharesState": "Enabled",
  "dnsEndpointType": "Standard",
  "allowCrossTenantReplicationToAzureBackup": true
}
}
@enduml
