@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureResourceGroups(cloud_shell_storage_westeurope, 'cloud-shell-storage-westeurope', 'Azure Resource Group')

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(csb100320041428ff8f, 'csb100320041428ff8f', 'Microsoft.Storage/storageAccounts')
Rel(cloud_shell_storage_westeurope, csb100320041428ff8f, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(csb1003200033b9b8b7, 'csb1003200033b9b8b7', 'Microsoft.Storage/storageAccounts')
Rel(cloud_shell_storage_westeurope, csb1003200033b9b8b7, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
