@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureResourceGroups(dna_test, 'dna-test', 'Azure Resource Group')

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(dna_test_kv_fhca, 'dna-test-kv-fhca', 'Microsoft.KeyVault/vaults')
Rel(dna_test, dna_test_kv_fhca, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureAvailabiltySet.puml
AzureAvailabiltySet(t_dna_rhel_avail, 't-dna-rhel-avail', 'Microsoft.Compute/availabilitySets')
Rel(dna_test, t_dna_rhel_avail, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(t_dna_rhel1_datadisk1, 't-dna-rhel1-datadisk1', 'Microsoft.Compute/disks')
Rel(dna_test, t_dna_rhel1_datadisk1, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(t_dna_rhel1_nic, 't-dna-rhel1-nic', 'Microsoft.Network/networkInterfaces')
Rel(dna_test, t_dna_rhel1_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(t_dna_rhel1, 't-dna-rhel1', 'Microsoft.Compute/virtualMachines')
Rel(dna_test, t_dna_rhel1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(t_dna_rhel1_osdisk, 't-dna-rhel1-osdisk', 'Microsoft.Compute/disks')
Rel(dna_test, t_dna_rhel1_osdisk, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
