@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureResourceGroups(maksym_maintenanceConfig, 'maksym-maintenanceConfig', 'Azure Resource Group')

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(vmmfdiagsettgs, 'vmmfdiagsettgs', 'Microsoft.Storage/storageAccounts')
Rel(maksym_maintenanceConfig, vmmfdiagsettgs, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(vm_mf_kv_gssb, 'vm-mf-kv-gssb', 'Microsoft.KeyVault/vaults')
Rel(maksym_maintenanceConfig, vm_mf_kv_gssb, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureAvailabiltySet.puml
AzureAvailabiltySet(vm_mf_avail, 'vm-mf-avail', 'Microsoft.Compute/availabilitySets')
Rel(maksym_maintenanceConfig, vm_mf_avail, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(vm_mf1_datadisk1, 'vm-mf1-datadisk1', 'Microsoft.Compute/disks')
Rel(maksym_maintenanceConfig, vm_mf1_datadisk1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(vm_mf2_datadisk1, 'vm-mf2-datadisk1', 'Microsoft.Compute/disks')
Rel(maksym_maintenanceConfig, vm_mf2_datadisk1, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(vm_mf2_nic, 'vm-mf2-nic', 'Microsoft.Network/networkInterfaces')
Rel(maksym_maintenanceConfig, vm_mf2_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(vm_mf1_nic, 'vm-mf1-nic', 'Microsoft.Network/networkInterfaces')
Rel(maksym_maintenanceConfig, vm_mf1_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(vm_mf2, 'vm-mf2', 'Microsoft.Compute/virtualMachines')
Rel(maksym_maintenanceConfig, vm_mf2, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(vm_mf1, 'vm-mf1', 'Microsoft.Compute/virtualMachines')
Rel(maksym_maintenanceConfig, vm_mf1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(vm_mf1_osdisk, 'vm-mf1-osdisk', 'Microsoft.Compute/disks')
Rel(maksym_maintenanceConfig, vm_mf1_osdisk, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(vm_mf2_osdisk, 'vm-mf2-osdisk', 'Microsoft.Compute/disks')
Rel(maksym_maintenanceConfig, vm_mf2_osdisk, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
