@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureResourceGroups(maksym_finops_private, 'maksym-finops-private', 'Azure Resource Group')

!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
AzureVirtualNetwork(finopshub_vnet_norwayeast, 'finopshub-vnet-norwayeast', 'Microsoft.Network/virtualNetworks')
Rel(maksym_finops_private, finopshub_vnet_norwayeast, 'Uses', 'Resource' )

!includeurl AzurePuml/Databases/AzureDataFactory.puml
AzureDataFactory(finopshub_engine_6xisw66qnemiw, 'finopshub-engine-6xisw66qnemiw', 'Microsoft.DataFactory/factories')
Rel(maksym_finops_private, finopshub_engine_6xisw66qnemiw, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNSG.puml
AzureNSG(finopshub_vnet_norwayeast_nsg, 'finopshub-vnet-norwayeast-nsg', 'Microsoft.Network/networkSecurityGroups')
Rel(maksym_finops_private, finopshub_vnet_norwayeast_nsg, 'Uses', 'Resource' )

!includeurl AzurePuml/Identity/AzureManagedIdentity.puml
AzureManagedIdentity(finopshub6xisw66qnemiw_blobManager, 'finopshub6xisw66qnemiw_blobManager', 'Microsoft.ManagedIdentity/userAssignedIdentities')
Rel(maksym_finops_private, finopshub6xisw66qnemiw_blobManager, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(finopshub6xisw66qnemiw, 'finopshub6xisw66qnemiw', 'Microsoft.Storage/storageAccounts')
Rel(maksym_finops_private, finopshub6xisw66qnemiw, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(finscript6xisw66qnemiw, 'finscript6xisw66qnemiw', 'Microsoft.Storage/storageAccounts')
Rel(maksym_finops_private, finscript6xisw66qnemiw, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(finopshub_6xisw66qnemiw, 'finopshub-6xisw66qnemiw', 'Microsoft.KeyVault/vaults')
Rel(maksym_finops_private, finopshub_6xisw66qnemiw, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzurePrivateLink.puml
AzurePrivateLink(finopshub_6xisw66qnemiw_ep, 'finopshub-6xisw66qnemiw-ep', 'Microsoft.Network/privateEndpoints')
Rel(maksym_finops_private, finopshub_6xisw66qnemiw_ep, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(finopshub_6xisw66qnemiw_ep.nic.52b1b6f3_41ba_4e3e_a937_a08516ad44b6, 'finopshub-6xisw66qnemiw-ep.nic.52b1b6f3-41ba-4e3e-a937-a08516ad44b6', 'Microsoft.Network/networkInterfaces')
Rel(maksym_finops_private, finopshub_6xisw66qnemiw_ep.nic.52b1b6f3_41ba_4e3e_a937_a08516ad44b6, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzurePrivateLink.puml
AzurePrivateLink(finscript6xisw66qnemiw_blob_ep, 'finscript6xisw66qnemiw-blob-ep', 'Microsoft.Network/privateEndpoints')
Rel(maksym_finops_private, finscript6xisw66qnemiw_blob_ep, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzurePrivateLink.puml
AzurePrivateLink(finopshub6xisw66qnemiw_dfs_ep, 'finopshub6xisw66qnemiw-dfs-ep', 'Microsoft.Network/privateEndpoints')
Rel(maksym_finops_private, finopshub6xisw66qnemiw_dfs_ep, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzurePrivateLink.puml
AzurePrivateLink(finopshub6xisw66qnemiw_blob_ep, 'finopshub6xisw66qnemiw-blob-ep', 'Microsoft.Network/privateEndpoints')
Rel(maksym_finops_private, finopshub6xisw66qnemiw_blob_ep, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(finscript6xisw66qnemiw_blob_ep.nic.28e1bf09_abd5_4379_b4fa_fe7ca5e34e03, 'finscript6xisw66qnemiw-blob-ep.nic.28e1bf09-abd5-4379-b4fa-fe7ca5e34e03', 'Microsoft.Network/networkInterfaces')
Rel(maksym_finops_private, finscript6xisw66qnemiw_blob_ep.nic.28e1bf09_abd5_4379_b4fa_fe7ca5e34e03, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(finopshub6xisw66qnemiw_dfs_ep.nic.e81b10be_a412_46f6_aa0f_bdb6b558d633, 'finopshub6xisw66qnemiw-dfs-ep.nic.e81b10be-a412-46f6-aa0f-bdb6b558d633', 'Microsoft.Network/networkInterfaces')
Rel(maksym_finops_private, finopshub6xisw66qnemiw_dfs_ep.nic.e81b10be_a412_46f6_aa0f_bdb6b558d633, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(finopshub6xisw66qnemiw_blob_ep.nic.1ba02160_4050_4902_a685_3221f654cc80, 'finopshub6xisw66qnemiw-blob-ep.nic.1ba02160-4050-4902-a685-3221f654cc80', 'Microsoft.Network/networkInterfaces')
Rel(maksym_finops_private, finopshub6xisw66qnemiw_blob_ep.nic.1ba02160_4050_4902_a685_3221f654cc80, 'Uses', 'Resource' )

!includeurl AzurePuml/Identity/AzureManagedIdentity.puml
AzureManagedIdentity(finopshub_engine_6xisw66qnemiw_triggerManager, 'finopshub-engine-6xisw66qnemiw_triggerManager', 'Microsoft.ManagedIdentity/userAssignedIdentities')
Rel(maksym_finops_private, finopshub_engine_6xisw66qnemiw_triggerManager, 'Uses', 'Resource' )

!includeurl AzurePuml/Integration/AzureSystemTopic.puml
AzureSystemTopic(finopshub6xisw66qnemiw_7f342013_ed6e_4276_bf0d_874961d976b8, 'finopshub6xisw66qnemiw-7f342013-ed6e-4276-bf0d-874961d976b8', 'Microsoft.EventGrid/systemTopics')
Rel(maksym_finops_private, finopshub6xisw66qnemiw_7f342013_ed6e_4276_bf0d_874961d976b8, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
