@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureResourceGroups(maksym_finops, 'maksym-finops', 'Azure Resource Group')

!includeurl AzurePuml/Databases/AzureDataFactory.puml
AzureDataFactory(MyHubPublic_engine_tj5eravonizvq, 'MyHubPublic-engine-tj5eravonizvq', 'Microsoft.DataFactory/factories')
Rel(maksym_finops, MyHubPublic_engine_tj5eravonizvq, 'Uses', 'Resource' )

!includeurl AzurePuml/Identity/AzureManagedIdentity.puml
AzureManagedIdentity(myhubpublictj5eravonizvq_blobManager, 'myhubpublictj5eravonizvq_blobManager', 'Microsoft.ManagedIdentity/userAssignedIdentities')
Rel(maksym_finops, myhubpublictj5eravonizvq_blobManager, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(myhubpublictj5eravonizvq, 'myhubpublictj5eravonizvq', 'Microsoft.Storage/storageAccounts')
Rel(maksym_finops, myhubpublictj5eravonizvq, 'Uses', 'Resource' )

!includeurl AzurePuml/Identity/AzureManagedIdentity.puml
AzureManagedIdentity(MyHubPublic_engine_tj5eravonizvq_triggerManager, 'MyHubPublic-engine-tj5eravonizvq_triggerManager', 'Microsoft.ManagedIdentity/userAssignedIdentities')
Rel(maksym_finops, MyHubPublic_engine_tj5eravonizvq_triggerManager, 'Uses', 'Resource' )

!includeurl AzurePuml/Integration/AzureSystemTopic.puml
AzureSystemTopic(myhubpublictj5eravonizvq_a0d0457d_f302_4876_ae91_5bc42dbd3223, 'myhubpublictj5eravonizvq-a0d0457d-f302-4876-ae91-5bc42dbd3223', 'Microsoft.EventGrid/systemTopics')
Rel(maksym_finops, myhubpublictj5eravonizvq_a0d0457d_f302_4876_ae91_5bc42dbd3223, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
