@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureResourceGroups(rg_aleksander, 'rg-aleksander', 'Azure Resource Group')

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(sandboxbcptest, 'sandboxbcptest', 'Microsoft.Storage/storageAccounts')
Rel(rg_aleksander, sandboxbcptest, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureAvailabiltySet.puml
AzureAvailabiltySet(d_awh_wm_avail, 'd-awh-wm-avail', 'Microsoft.Compute/availabilitySets')
Rel(rg_aleksander, d_awh_wm_avail, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(d_awh_wm1_datadisk1, 'd-awh-wm1-datadisk1', 'Microsoft.Compute/disks')
Rel(rg_aleksander, d_awh_wm1_datadisk1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(d_awh_wm1_osdisk, 'd-awh-wm1-osdisk', 'Microsoft.Compute/disks')
Rel(rg_aleksander, d_awh_wm1_osdisk, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureSharedImageGallery.puml
AzureSharedImageGallery(devtestcomputegallery, 'devtestcomputegallery', 'Microsoft.Compute/galleries')
Rel(rg_aleksander, devtestcomputegallery, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(dawhwmdiagsett3f, 'dawhwmdiagsett3f', 'Microsoft.Storage/storageAccounts')
Rel(rg_aleksander, dawhwmdiagsett3f, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(d_awh_wm_kv_3fpr, 'd-awh-wm-kv-3fpr', 'Microsoft.KeyVault/vaults')
Rel(rg_aleksander, d_awh_wm_kv_3fpr, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(d_awh_wm1_nic, 'd-awh-wm1-nic', 'Microsoft.Network/networkInterfaces')
Rel(rg_aleksander, d_awh_wm1_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(d_awh_wm1, 'd-awh-wm1', 'Microsoft.Compute/virtualMachines')
Rel(rg_aleksander, d_awh_wm1, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(dawhappwmdiagsett3f, 'dawhappwmdiagsett3f', 'Microsoft.Storage/storageAccounts')
Rel(rg_aleksander, dawhappwmdiagsett3f, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(d_awh_appwm_kv_3fpr, 'd-awh-appwm-kv-3fpr', 'Microsoft.KeyVault/vaults')
Rel(rg_aleksander, d_awh_appwm_kv_3fpr, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureAvailabiltySet.puml
AzureAvailabiltySet(d_awh_appwm_avail, 'd-awh-appwm-avail', 'Microsoft.Compute/availabilitySets')
Rel(rg_aleksander, d_awh_appwm_avail, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(d_awh_appwm1_datadisk1, 'd-awh-appwm1-datadisk1', 'Microsoft.Compute/disks')
Rel(rg_aleksander, d_awh_appwm1_datadisk1, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(d_awh_appwm1_nic, 'd-awh-appwm1-nic', 'Microsoft.Network/networkInterfaces')
Rel(rg_aleksander, d_awh_appwm1_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(d_awh_appwm1, 'd-awh-appwm1', 'Microsoft.Compute/virtualMachines')
Rel(rg_aleksander, d_awh_appwm1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(d_awh_appwm1_osdisk, 'd-awh-appwm1-osdisk', 'Microsoft.Compute/disks')
Rel(rg_aleksander, d_awh_appwm1_osdisk, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(dawhstorage, 'dawhstorage', 'Microsoft.Storage/storageAccounts')
Rel(rg_aleksander, dawhstorage, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(d_awhsandbox_kv, 'd-awhsandbox-kv', 'Microsoft.KeyVault/vaults')
Rel(rg_aleksander, d_awhsandbox_kv, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
