@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureResourceGroups(rg_bjornjorgen, 'rg-bjornjorgen', 'Azure Resource Group')

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(testbjs2, 'testbjs2', 'Microsoft.Storage/storageAccounts')
Rel(rg_bjornjorgen, testbjs2, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNSG.puml
AzureNSG(basicNsgvnet_norwayeast_nic01, 'basicNsgvnet-norwayeast-nic01', 'Microsoft.Network/networkSecurityGroups')
Rel(rg_bjornjorgen, basicNsgvnet_norwayeast_nic01, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
AzureVirtualNetwork(vnet_norwayeast, 'vnet-norwayeast', 'Microsoft.Network/virtualNetworks')
Rel(rg_bjornjorgen, vnet_norwayeast, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachineScaleSet.puml
AzureVirtualMachineScaleSet(bjsScaleset1, 'bjsScaleset1', 'Microsoft.Compute/virtualMachineScaleSets')
Rel(rg_bjornjorgen, bjsScaleset1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(bjsScaleset1_ff6a1be6, 'bjsScaleset1_ff6a1be6', 'Microsoft.Compute/virtualMachines')
Rel(rg_bjornjorgen, bjsScaleset1_ff6a1be6, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(bjsScaleset1_bf585774, 'bjsScaleset1_bf585774', 'Microsoft.Compute/virtualMachines')
Rel(rg_bjornjorgen, bjsScaleset1_bf585774, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(bjsScaleset1_ff6a1be6_OsDisk_1_bbef783febe54664b36726be0739d16c, 'bjsScaleset1_ff6a1be6_OsDisk_1_bbef783febe54664b36726be0739d16c', 'Microsoft.Compute/disks')
Rel(rg_bjornjorgen, bjsScaleset1_ff6a1be6_OsDisk_1_bbef783febe54664b36726be0739d16c, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(bjsScaleset1_bf585774_OsDisk_1_c491f3779cb94873b00f269bbb890b2c, 'bjsScaleset1_bf585774_OsDisk_1_c491f3779cb94873b00f269bbb890b2c', 'Microsoft.Compute/disks')
Rel(rg_bjornjorgen, bjsScaleset1_bf585774_OsDisk_1_c491f3779cb94873b00f269bbb890b2c, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzurePublicIPAddress.puml
AzurePublicIPAddress(publicIp_vnet_norwayeast_nic01_28e3bab2, 'publicIp-vnet-norwayeast-nic01-28e3bab2', 'Microsoft.Network/publicIPAddresses')
Rel(rg_bjornjorgen, publicIp_vnet_norwayeast_nic01_28e3bab2, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzurePublicIPAddress.puml
AzurePublicIPAddress(publicIp_vnet_norwayeast_nic01_ebe7168c, 'publicIp-vnet-norwayeast-nic01-ebe7168c', 'Microsoft.Network/publicIPAddresses')
Rel(rg_bjornjorgen, publicIp_vnet_norwayeast_nic01_ebe7168c, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(vnet_norwayeast_nic01_28e3bab2, 'vnet-norwayeast-nic01-28e3bab2', 'Microsoft.Network/networkInterfaces')
Rel(rg_bjornjorgen, vnet_norwayeast_nic01_28e3bab2, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(vnet_norwayeast_nic01_ebe7168c, 'vnet-norwayeast-nic01-ebe7168c', 'Microsoft.Network/networkInterfaces')
Rel(rg_bjornjorgen, vnet_norwayeast_nic01_ebe7168c, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(tbjs2windiagsettk4, 'tbjs2windiagsettk4', 'Microsoft.Storage/storageAccounts')
Rel(rg_bjornjorgen, tbjs2windiagsettk4, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(t_bjs2_win_kv_k4l6, 't-bjs2-win-kv-k4l6', 'Microsoft.KeyVault/vaults')
Rel(rg_bjornjorgen, t_bjs2_win_kv_k4l6, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureAvailabiltySet.puml
AzureAvailabiltySet(t_bjs2_win_avail, 't-bjs2-win-avail', 'Microsoft.Compute/availabilitySets')
Rel(rg_bjornjorgen, t_bjs2_win_avail, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(t_bjs2_win1_nic, 't-bjs2-win1-nic', 'Microsoft.Network/networkInterfaces')
Rel(rg_bjornjorgen, t_bjs2_win1_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(t_bjs2_win1, 't-bjs2-win1', 'Microsoft.Compute/virtualMachines')
Rel(rg_bjornjorgen, t_bjs2_win1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(t_bjs2_win1_osdisk, 't-bjs2-win1-osdisk', 'Microsoft.Compute/disks')
Rel(rg_bjornjorgen, t_bjs2_win1_osdisk, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
