@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureResourceGroups(rg_daniel, 'rg-daniel', 'Azure Resource Group')

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(soctestsnap, 'soctestsnap', 'Microsoft.Storage/storageAccounts')
Rel(rg_daniel, soctestsnap, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureAutomation.puml
AzureAutomation(test_aa, 'test-aa', 'Microsoft.Automation/automationAccounts')
Rel(rg_daniel, test_aa, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
