@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureResourceGroups(rg_email, 'rg-email', 'Azure Resource Group')

!includeurl AzurePuml/Analytics/AzureLogAnalyticsWorkspace.puml
AzureLogAnalyticsWorkspace(p_log_emailpoc, 'p-log-emailpoc', 'Microsoft.OperationalInsights/workspaces')
Rel(rg_email, p_log_emailpoc, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
