@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureResourceGroups(rg_tom, 'rg-tom', 'Azure Resource Group')

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(pgithubbackupstorage, 'pgithubbackupstorage', 'Microsoft.Storage/storageAccounts')
Rel(rg_tom, pgithubbackupstorage, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureAutomation.puml
AzureAutomation(GitHubBackupAutomation, 'GitHubBackupAutomation', 'Microsoft.Automation/automationAccounts')
Rel(rg_tom, GitHubBackupAutomation, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(test12345789, 'test12345789', 'Microsoft.KeyVault/vaults')
Rel(rg_tom, test12345789, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(dfrvgtbhnjmk, 'dfrvgtbhnjmk', 'Microsoft.Storage/storageAccounts')
Rel(rg_tom, dfrvgtbhnjmk, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(mediauploadtest, 'mediauploadtest', 'Microsoft.Storage/storageAccounts')
Rel(rg_tom, mediauploadtest, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
