@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "version": "2018-06-01",
  "createTime": "2025-04-11T15:45:39.0472927Z",
  "factoryStatistics": {
    "maxAllowedFactorySizeInGbUnits": 0,
    "maxAllowedResourceCount": 0,
    "factorySizeInGbUnits": 0,
    "totalResourceCount": 0
  },
  "globalConfigurations": {
    "PipelineBillingEnabled": "true"
  }
}
}
@enduml
