@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "tenantId": "0",
  "isolationScope": "None",
  "principalId": "4af45955-0f49-4b1a-83d8-63551557d821",
  "clientId": "ae05561c-cfa4-4310-8cb8-1fcf3f1484f8"
}
}
@enduml
