@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "metricResourceId": "d72473a8-cfaf-4258-9a78-7d3c80ddab13",
  "source": "/subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/resourceGroups/maksym-finops/providers/microsoft.storage/storageaccounts/myhubpublictj5eravonizvq",
  "topicType": "microsoft.storage.storageaccounts"
}
}
@enduml
