@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "publicNetworkAccess": "Enabled",
  "networkAccessPolicy": "AllowAll",
  "timeCreated": "2024-12-07T10:08:52.6789836Z",
  "diskSizeGB": 128,
  "encryption": {
    "type": "EncryptionAtRestWithPlatformKey"
  },
  "diskSizeBytes": 137438953472,
  "creationData": {
    "createOption": "FromImage",
    "imageReference": {
      "id": "/Subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/Providers/Microsoft.Compute/Locations/NorwayEast/Publishers/RedHat/ArtifactTypes/VMImage/Offers/RHEL/Skus/8-gen2/Versions/8.0.20191024"
    }
  },
  "hyperVGeneration": "V2",
  "supportedCapabilities": {
    "architecture": "x64",
    "acceleratedNetwork": true
  },
  "diskState": "Attached",
  "uniqueId": "3eefdf39-e352-4eda-96f9-a7526d24d84a",
  "LastOwnershipUpdateTime": "2024-12-07T10:08:52.6789836Z",
  "osType": "Linux",
  "diskIOPSReadWrite": 500,
  "diskMBpsReadWrite": 100,
  "tier": "P10"
}
}
@enduml
