@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "resourceGuid": "a6ca5612-bba7-41fe-bfe0-fbd896a88de0",
  "ipConfigurations": [],
  "networkInterfaces": [
    {
      "id": "/subscriptions/0/resourceGroups/maksym-finops-private/providers/Microsoft.Network/networkInterfaces/finopshub-6xisw66qnemiw-ep.nic.52b1b6f3-41ba-4e3e-a937-a08516ad44b6"
    }
  ],
  "subnet": {
    "id": "/subscriptions/0/resourceGroups/maksym-finops-private/providers/Microsoft.Network/virtualNetworks/finopshub-vnet-norwayeast/subnets/private-endpoint-subnet"
  },
  "privateLinkServiceConnections": [
    {
      "properties": {
        "provisioningState": "Succeeded",
        "privateLinkServiceConnectionState": {
          "description": "",
          "status": "Approved",
          "actionsRequired": "None"
        },
        "privateLinkServiceId": "/subscriptions/0/resourceGroups/maksym-finops-private/providers/Microsoft.KeyVault/vaults/finopshub-6xisw66qnemiw",
        "groupIds": [
          "vault"
        ]
      },
      "name": "keyVaultLink",
      "type": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections",
      "id": "/subscriptions/0/resourceGroups/maksym-finops-private/providers/Microsoft.Network/privateEndpoints/finopshub-6xisw66qnemiw-ep/privateLinkServiceConnections/keyVaultLink",
      "etag": "W/\"929e18af-a3a7-44fd-af68-0651183b394b\""
    }
  ],
  "manualPrivateLinkServiceConnections": [],
  "customDnsConfigs": [],
  "customNetworkInterfaceName": "",
  "ipVersionType": "IPv4"
}
}
@enduml
