@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "tenantId": "67508d80-2b69-484e-ab62-ab263ca94733",
  "principalId": "52d80ceb-dbae-4ca5-b4a2-fbb13409c031",
  "isolationScope": "None",
  "clientId": "9be910c1-62a3-4224-a448-a5f2b6af7959"
}
}
@enduml
