@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "publicNetworkAccess": "Enabled",
  "privateEndpointConnections": [
    {
      "properties": {
        "provisioningState": "Succeeded",
        "privateLinkServiceConnectionState": {
          "status": "Approved",
          "actionsRequired": "None"
        },
        "privateEndpoint": {
          "id": "/subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/resourceGroups/maksym-finops-private/providers/Microsoft.Network/privateEndpoints/finopshub-6xisw66qnemiw-ep"
        }
      },
      "id": "/subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/resourceGroups/maksym-finops-private/providers/Microsoft.KeyVault/vaults/finopshub-6xisw66qnemiw/privateEndpointConnections/keyVaultLink"
    },
    {
      "properties": {
        "provisioningState": "Succeeded",
        "privateLinkServiceConnectionState": {
          "description": "Requested by DataFactory:finopshub-engine-6xisw66qnemiw, Name:finopshub-6xisw66qnemiw",
          "status": "Pending",
          "actionsRequired": "None"
        },
        "privateEndpoint": {
          "id": "/subscriptions/1b5ab6d2-a8ac-4bf5-bd65-32fa94881a8a/resourceGroups/vnet-1b5ab6d2-norwayeast-85-rg/providers/Microsoft.Network/privateEndpoints/finopshub-engine-6xisw66qnemiw.finopshub-6xisw66qnemiw"
        }
      },
      "id": "/subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/resourceGroups/maksym-finops-private/providers/Microsoft.KeyVault/vaults/finopshub-6xisw66qnemiw/privateEndpointConnections/finopshub-engine-6xisw66qnemiw.finopshub-6xisw66qnemiw-conn"
    }
  ],
  "networkAcls": {
    "virtualNetworkRules": [],
    "defaultAction": "Deny",
    "ipRules": [],
    "bypass": "AzureServices"
  },
  "tenantId": "67508d80-2b69-484e-ab62-ab263ca94733",
  "enabledForTemplateDeployment": true,
  "sku": {
    "name": "premium",
    "family": "A"
  },
  "enableRbacAuthorization": false,
  "enabledForDiskEncryption": true,
  "enabledForDeployment": true,
  "accessPolicies": [
    {
      "tenantId": "67508d80-2b69-484e-ab62-ab263ca94733",
      "permissions": {
        "secrets": [
          "get"
        ]
      },
      "objectId": "49d4a749-54f5-4adc-8e15-8fc82f0af192"
    }
  ],
  "softDeleteRetentionInDays": 90,
  "enableSoftDelete": true,
  "vaultUri": "https://finopshub-6xisw66qnemiw.vault.azure.net/"
}
}
@enduml
