@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "tenantId": "0",
  "principalId": "42109dd3-3da9-43c8-92b1-89aed2fc74c3",
  "isolationScope": "None",
  "clientId": "2f5dc019-d297-4466-9061-ab2e377c3945"
}
}
@enduml
