@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "enableAcceleratedNetworking": false,
  "resourceGuid": "6464e7e8-31f2-42d3-b365-142bb5b9b22d",
  "defaultOutboundConnectivityEnabled": false,
  "disableTcpStateTracking": false,
  "vnetEncryptionSupported": false,
  "ipConfigurations": [
    {
      "properties": {
        "provisioningState": "Succeeded",
        "privateIPAddressVersion": "IPv4",
        "privateIPAllocationMethod": "Dynamic",
        "privateIPAddress": "10.104.13.6",
        "primary": true,
        "subnet": {
          "id": "/subscriptions/0/resourceGroups/maksym-finops-private/providers/Microsoft.Network/virtualNetworks/finopshub-vnet-norwayeast/subnets/private-endpoint-subnet"
        },
        "privateLinkConnectionProperties": {
          "requiredMemberName": "dfs",
          "groupId": "dfs",
          "fqdns": [
            "finopshub6xisw66qnemiw.dfs.core.windows.net"
          ]
        }
      },
      "name": "privateEndpointIpConfig.1b1b23fb-c0fa-4cfb-9fce-bb0d6ad7fead",
      "type": "Microsoft.Network/networkInterfaces/ipConfigurations",
      "id": "/subscriptions/0/resourceGroups/maksym-finops-private/providers/Microsoft.Network/networkInterfaces/finopshub6xisw66qnemiw-dfs-ep.nic.e81b10be-a412-46f6-aa0f-bdb6b558d633/ipConfigurations/privateEndpointIpConfig.1b1b23fb-c0fa-4cfb-9fce-bb0d6ad7fead",
      "etag": "W/\"0003c767-8f3b-4383-93fc-691f6eecc77d\""
    }
  ],
  "enableIPForwarding": false,
  "tapConfigurations": [],
  "hostedWorkloads": [],
  "allowPort25Out": true,
  "auxiliaryMode": "None",
  "dnsSettings": {
    "appliedDnsServers": [],
    "internalDomainNameSuffix": "pga3ftvdtvwunhdl1tdi3l02qa.oslx.internal.cloudapp.net",
    "dnsServers": []
  },
  "auxiliarySku": "None",
  "macAddress": "",
  "nicType": "Standard",
  "privateEndpoint": {
    "id": "/subscriptions/0/resourceGroups/maksym-finops-private/providers/Microsoft.Network/privateEndpoints/finopshub6xisw66qnemiw-dfs-ep"
  }
}
}
@enduml
