@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "maxNumberOfVirtualNetworkLinksWithRegistration": 100,
  "numberOfVirtualNetworkLinksWithRegistration": 0,
  "maxNumberOfVirtualNetworkLinks": 1000,
  "numberOfVirtualNetworkLinks": 1,
  "maxNumberOfRecordSets": 25000,
  "numberOfRecordSets": 1,
  "internalId": "SW1tdXRhYmxlWm9uZUlkZW50aXR5Ozc4YmZjMDNjLWVhNjktNDA2OC1iM2Q3LWRiM2U5MzNhZWY4ZTsw"
}
}
@enduml
