@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureSubscription.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureSubscription(KLP_LZ_SRE_playground_Sandbox, 'KLP LZ SRE playground Sandbox', 'Azure Landing Zone')
AzureResourceGroups(lz_norwayeast, 'lz-norwayeast', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, lz_norwayeast, 'Uses', 'Subscription' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(lz_sec_solution_delete_alert, 'lz-sec-solution-delete-alert', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, lz_sec_solution_delete_alert, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(lz_net_nsg_write_alert, 'lz-net-nsg-write-alert', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, lz_net_nsg_write_alert, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(lz_sql_fw_delete_alert, 'lz-sql-fw-delete-alert', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, lz_sql_fw_delete_alert, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(lz_net_nsg_delete_alert, 'lz-net-nsg-delete-alert', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, lz_net_nsg_delete_alert, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(lz_net_nsgrule_write_alert, 'lz-net-nsgrule-write-alert', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, lz_net_nsgrule_write_alert, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(lz_auth_policy_delete_alert, 'lz-auth-policy-delete-alert', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, lz_auth_policy_delete_alert, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(lz_auth_policy_write_alert, 'lz-auth-policy-write-alert', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, lz_auth_policy_write_alert, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(lz_sql_fw_write_alert, 'lz-sql-fw-write-alert', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, lz_sql_fw_write_alert, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(lz_sec_solution_write_alert, 'lz-sec-solution-write-alert', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, lz_sec_solution_write_alert, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(lz_net_nsgrule_delete_alert, 'lz-net-nsgrule-delete-alert', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, lz_net_nsgrule_delete_alert, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureRecoveryServiceVault.puml
AzureRecoveryServiceVault(lz_norwayeast_rsv, 'lz-norwayeast-rsv', 'Microsoft.RecoveryServices/vaults')
Rel(lz_norwayeast, lz_norwayeast_rsv, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(Alert___Service_Issues, 'Alert - Service Issues', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, Alert___Service_Issues, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(Alert___Security_Advisory, 'Alert - Security Advisory', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, Alert___Security_Advisory, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(Alert___Planned_Maintenance, 'Alert - Planned Maintenance', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, Alert___Planned_Maintenance, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureMonitor.puml
AzureMonitor(Alert___Health_Advisories, 'Alert - Health Advisories', 'Microsoft.Insights/activityLogAlerts')
Rel(lz_norwayeast, Alert___Health_Advisories, 'Uses', 'Resource' )

AzureResourceGroups(NetworkWatcherRG, 'NetworkWatcherRG', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, NetworkWatcherRG, 'Uses', 'Subscription' )

AzureResourceGroups(rg_email, 'rg-email', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_email, 'Uses', 'Subscription' )

!includeurl AzurePuml/Analytics/AzureLogAnalyticsWorkspace.puml
AzureLogAnalyticsWorkspace(p_log_emailpoc, 'p-log-emailpoc', 'Microsoft.OperationalInsights/workspaces')
Rel(rg_email, p_log_emailpoc, 'Uses', 'Resource' )

AzureResourceGroups(lz_network_norwayeast, 'lz-network-norwayeast', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, lz_network_norwayeast, 'Uses', 'Subscription' )

!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
AzureVirtualNetwork(lz_network_norwayeast_vnet, 'lz-network-norwayeast-vnet', 'Microsoft.Network/virtualNetworks')
Rel(lz_network_norwayeast, lz_network_norwayeast_vnet, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNSG.puml
AzureNSG(lz_network_norwayeast_vnet_dna_test_1_nsg, 'lz-network-norwayeast-vnet-dna-test-1-nsg', 'Microsoft.Network/networkSecurityGroups')
Rel(lz_network_norwayeast, lz_network_norwayeast_vnet_dna_test_1_nsg, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNSG.puml
AzureNSG(lz_network_norwayeast_vnet_maksym_maintenanceconfig_nsg, 'lz-network-norwayeast-vnet-maksym-maintenanceconfig-nsg', 'Microsoft.Network/networkSecurityGroups')
Rel(lz_network_norwayeast, lz_network_norwayeast_vnet_maksym_maintenanceconfig_nsg, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNSG.puml
AzureNSG(lz_network_norwayeast_vnet_adds_test_nsg, 'lz-network-norwayeast-vnet-adds-test-nsg', 'Microsoft.Network/networkSecurityGroups')
Rel(lz_network_norwayeast, lz_network_norwayeast_vnet_adds_test_nsg, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzurePublicIPAddress.puml
AzurePublicIPAddress(lz_network_norwayeast_vnet_ip, 'lz-network-norwayeast-vnet-ip', 'Microsoft.Network/publicIPAddresses')
Rel(lz_network_norwayeast, lz_network_norwayeast_vnet_ip, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureBastion.puml
AzureBastion(lz_network_norwayeast_vnet_bastion, 'lz-network-norwayeast-vnet-bastion', 'Microsoft.Network/bastionHosts')
Rel(lz_network_norwayeast, lz_network_norwayeast_vnet_bastion, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNSG.puml
AzureNSG(lz_network_norwayeast_vnet_default_nsg, 'lz-network-norwayeast-vnet-default-nsg', 'Microsoft.Network/networkSecurityGroups')
Rel(lz_network_norwayeast, lz_network_norwayeast_vnet_default_nsg, 'Uses', 'Resource' )

AzureResourceGroups(linux_test, 'linux-test', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, linux_test, 'Uses', 'Subscription' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(t_linux_vm_nic, 't-linux-vm-nic', 'Microsoft.Network/networkInterfaces')
Rel(linux_test, t_linux_vm_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(t_linux_vm, 't-linux-vm', 'Microsoft.Compute/virtualMachines')
Rel(linux_test, t_linux_vm, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(t_linux_vm_osdisk, 't-linux-vm-osdisk', 'Microsoft.Compute/disks')
Rel(linux_test, t_linux_vm_osdisk, 'Uses', 'Resource' )

AzureResourceGroups(rg_audun, 'rg-audun', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_audun, 'Uses', 'Subscription' )

!includeurl AzurePuml/Integration/AzureLogicApps.puml
AzureLogicApps(FailedEmails, 'FailedEmails', 'Microsoft.Logic/workflows')
Rel(rg_audun, FailedEmails, 'Uses', 'Resource' )

!includeurl AzurePuml/Integration/AzureLogicApps.puml
AzureLogicApps(p_mails_logic, 'p-mails-logic', 'Microsoft.Logic/workflows')
Rel(rg_audun, p_mails_logic, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(sweethomealabamaandback, 'sweethomealabamaandback', 'Microsoft.Storage/storageAccounts')
Rel(rg_audun, sweethomealabamaandback, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(svmaujtest_osdisk_20241128_110010, 'svmaujtest-osdisk-20241128-110010', 'Microsoft.Compute/disks')
Rel(rg_audun, svmaujtest_osdisk_20241128_110010, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(svmaujtest_datadisk_000_20241128_110010, 'svmaujtest-datadisk-000-20241128-110010', 'Microsoft.Compute/disks')
Rel(rg_audun, svmaujtest_datadisk_000_20241128_110010, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(s_vm_aujtest_nic_68983728f2824ec69836f3235bd9dd73, 's-vm-aujtest-nic-68983728f2824ec69836f3235bd9dd73', 'Microsoft.Network/networkInterfaces')
Rel(rg_audun, s_vm_aujtest_nic_68983728f2824ec69836f3235bd9dd73, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(s_vm_aujtest, 's-vm-aujtest', 'Microsoft.Compute/virtualMachines')
Rel(rg_audun, s_vm_aujtest, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
AzureVirtualNetwork(lz_network_norwayeast_vnet, 'lz-network-norwayeast-vnet', 'Microsoft.Network/virtualNetworks')
Rel(rg_audun, lz_network_norwayeast_vnet, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNSG.puml
AzureNSG(linux_backup_testNSG, 'linux-backup-testNSG', 'Microsoft.Network/networkSecurityGroups')
Rel(rg_audun, linux_backup_testNSG, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(linux_backup_testVMNic, 'linux-backup-testVMNic', 'Microsoft.Network/networkInterfaces')
Rel(rg_audun, linux_backup_testVMNic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(linux_backup_test, 'linux-backup-test', 'Microsoft.Compute/virtualMachines')
Rel(rg_audun, linux_backup_test, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(linux_backup_test_OsDisk_1_129dd182211d4de2935e0c81ea1c731a, 'linux-backup-test_OsDisk_1_129dd182211d4de2935e0c81ea1c731a', 'Microsoft.Compute/disks')
Rel(rg_audun, linux_backup_test_OsDisk_1_129dd182211d4de2935e0c81ea1c731a, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(LinuxDataDisk, 'LinuxDataDisk', 'Microsoft.Compute/disks')
Rel(rg_audun, LinuxDataDisk, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(linuxbackuptest_osdisk_20250114_100722, 'linuxbackuptest-osdisk-20250114-100722', 'Microsoft.Compute/disks')
Rel(rg_audun, linuxbackuptest_osdisk_20250114_100722, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(linuxbackuptest_osdisk_20250114_105029, 'linuxbackuptest-osdisk-20250114-105029', 'Microsoft.Compute/disks')
Rel(rg_audun, linuxbackuptest_osdisk_20250114_105029, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(linuxbackuptest_datadisk_000_20250114_105029, 'linuxbackuptest-datadisk-000-20250114-105029', 'Microsoft.Compute/disks')
Rel(rg_audun, linuxbackuptest_datadisk_000_20250114_105029, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(linuxbackuptest_osdisk_20250114_123657, 'linuxbackuptest-osdisk-20250114-123657', 'Microsoft.Compute/disks')
Rel(rg_audun, linuxbackuptest_osdisk_20250114_123657, 'Uses', 'Resource' )

AzureResourceGroups(rg_bjornjorgen, 'rg-bjornjorgen', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_bjornjorgen, 'Uses', 'Subscription' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(testbjs2, 'testbjs2', 'Microsoft.Storage/storageAccounts')
Rel(rg_bjornjorgen, testbjs2, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNSG.puml
AzureNSG(basicNsgvnet_norwayeast_nic01, 'basicNsgvnet-norwayeast-nic01', 'Microsoft.Network/networkSecurityGroups')
Rel(rg_bjornjorgen, basicNsgvnet_norwayeast_nic01, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
AzureVirtualNetwork(vnet_norwayeast, 'vnet-norwayeast', 'Microsoft.Network/virtualNetworks')
Rel(rg_bjornjorgen, vnet_norwayeast, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachineScaleSet.puml
AzureVirtualMachineScaleSet(bjsScaleset1, 'bjsScaleset1', 'Microsoft.Compute/virtualMachineScaleSets')
Rel(rg_bjornjorgen, bjsScaleset1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(bjsScaleset1_ff6a1be6, 'bjsScaleset1_ff6a1be6', 'Microsoft.Compute/virtualMachines')
Rel(rg_bjornjorgen, bjsScaleset1_ff6a1be6, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(bjsScaleset1_bf585774, 'bjsScaleset1_bf585774', 'Microsoft.Compute/virtualMachines')
Rel(rg_bjornjorgen, bjsScaleset1_bf585774, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(bjsScaleset1_ff6a1be6_OsDisk_1_bbef783febe54664b36726be0739d16c, 'bjsScaleset1_ff6a1be6_OsDisk_1_bbef783febe54664b36726be0739d16c', 'Microsoft.Compute/disks')
Rel(rg_bjornjorgen, bjsScaleset1_ff6a1be6_OsDisk_1_bbef783febe54664b36726be0739d16c, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(bjsScaleset1_bf585774_OsDisk_1_c491f3779cb94873b00f269bbb890b2c, 'bjsScaleset1_bf585774_OsDisk_1_c491f3779cb94873b00f269bbb890b2c', 'Microsoft.Compute/disks')
Rel(rg_bjornjorgen, bjsScaleset1_bf585774_OsDisk_1_c491f3779cb94873b00f269bbb890b2c, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzurePublicIPAddress.puml
AzurePublicIPAddress(publicIp_vnet_norwayeast_nic01_28e3bab2, 'publicIp-vnet-norwayeast-nic01-28e3bab2', 'Microsoft.Network/publicIPAddresses')
Rel(rg_bjornjorgen, publicIp_vnet_norwayeast_nic01_28e3bab2, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzurePublicIPAddress.puml
AzurePublicIPAddress(publicIp_vnet_norwayeast_nic01_ebe7168c, 'publicIp-vnet-norwayeast-nic01-ebe7168c', 'Microsoft.Network/publicIPAddresses')
Rel(rg_bjornjorgen, publicIp_vnet_norwayeast_nic01_ebe7168c, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(vnet_norwayeast_nic01_28e3bab2, 'vnet-norwayeast-nic01-28e3bab2', 'Microsoft.Network/networkInterfaces')
Rel(rg_bjornjorgen, vnet_norwayeast_nic01_28e3bab2, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(vnet_norwayeast_nic01_ebe7168c, 'vnet-norwayeast-nic01-ebe7168c', 'Microsoft.Network/networkInterfaces')
Rel(rg_bjornjorgen, vnet_norwayeast_nic01_ebe7168c, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(tbjs2windiagsettk4, 'tbjs2windiagsettk4', 'Microsoft.Storage/storageAccounts')
Rel(rg_bjornjorgen, tbjs2windiagsettk4, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(t_bjs2_win_kv_k4l6, 't-bjs2-win-kv-k4l6', 'Microsoft.KeyVault/vaults')
Rel(rg_bjornjorgen, t_bjs2_win_kv_k4l6, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureAvailabiltySet.puml
AzureAvailabiltySet(t_bjs2_win_avail, 't-bjs2-win-avail', 'Microsoft.Compute/availabilitySets')
Rel(rg_bjornjorgen, t_bjs2_win_avail, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(t_bjs2_win1_nic, 't-bjs2-win1-nic', 'Microsoft.Network/networkInterfaces')
Rel(rg_bjornjorgen, t_bjs2_win1_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(t_bjs2_win1, 't-bjs2-win1', 'Microsoft.Compute/virtualMachines')
Rel(rg_bjornjorgen, t_bjs2_win1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(t_bjs2_win1_osdisk, 't-bjs2-win1-osdisk', 'Microsoft.Compute/disks')
Rel(rg_bjornjorgen, t_bjs2_win1_osdisk, 'Uses', 'Resource' )

AzureResourceGroups(rg_daniel, 'rg-daniel', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_daniel, 'Uses', 'Subscription' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(soctestsnap, 'soctestsnap', 'Microsoft.Storage/storageAccounts')
Rel(rg_daniel, soctestsnap, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureAutomation.puml
AzureAutomation(test_aa, 'test-aa', 'Microsoft.Automation/automationAccounts')
Rel(rg_daniel, test_aa, 'Uses', 'Resource' )

AzureResourceGroups(rg_aleksander, 'rg-aleksander', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_aleksander, 'Uses', 'Subscription' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(sandboxbcptest, 'sandboxbcptest', 'Microsoft.Storage/storageAccounts')
Rel(rg_aleksander, sandboxbcptest, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureAvailabiltySet.puml
AzureAvailabiltySet(d_awh_wm_avail, 'd-awh-wm-avail', 'Microsoft.Compute/availabilitySets')
Rel(rg_aleksander, d_awh_wm_avail, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(d_awh_wm1_datadisk1, 'd-awh-wm1-datadisk1', 'Microsoft.Compute/disks')
Rel(rg_aleksander, d_awh_wm1_datadisk1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(d_awh_wm1_osdisk, 'd-awh-wm1-osdisk', 'Microsoft.Compute/disks')
Rel(rg_aleksander, d_awh_wm1_osdisk, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureSharedImageGallery.puml
AzureSharedImageGallery(devtestcomputegallery, 'devtestcomputegallery', 'Microsoft.Compute/galleries')
Rel(rg_aleksander, devtestcomputegallery, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(dawhwmdiagsett3f, 'dawhwmdiagsett3f', 'Microsoft.Storage/storageAccounts')
Rel(rg_aleksander, dawhwmdiagsett3f, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(d_awh_wm_kv_3fpr, 'd-awh-wm-kv-3fpr', 'Microsoft.KeyVault/vaults')
Rel(rg_aleksander, d_awh_wm_kv_3fpr, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(d_awh_wm1_nic, 'd-awh-wm1-nic', 'Microsoft.Network/networkInterfaces')
Rel(rg_aleksander, d_awh_wm1_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(d_awh_wm1, 'd-awh-wm1', 'Microsoft.Compute/virtualMachines')
Rel(rg_aleksander, d_awh_wm1, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(dawhappwmdiagsett3f, 'dawhappwmdiagsett3f', 'Microsoft.Storage/storageAccounts')
Rel(rg_aleksander, dawhappwmdiagsett3f, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(d_awh_appwm_kv_3fpr, 'd-awh-appwm-kv-3fpr', 'Microsoft.KeyVault/vaults')
Rel(rg_aleksander, d_awh_appwm_kv_3fpr, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureAvailabiltySet.puml
AzureAvailabiltySet(d_awh_appwm_avail, 'd-awh-appwm-avail', 'Microsoft.Compute/availabilitySets')
Rel(rg_aleksander, d_awh_appwm_avail, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(d_awh_appwm1_datadisk1, 'd-awh-appwm1-datadisk1', 'Microsoft.Compute/disks')
Rel(rg_aleksander, d_awh_appwm1_datadisk1, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(d_awh_appwm1_nic, 'd-awh-appwm1-nic', 'Microsoft.Network/networkInterfaces')
Rel(rg_aleksander, d_awh_appwm1_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(d_awh_appwm1, 'd-awh-appwm1', 'Microsoft.Compute/virtualMachines')
Rel(rg_aleksander, d_awh_appwm1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(d_awh_appwm1_osdisk, 'd-awh-appwm1-osdisk', 'Microsoft.Compute/disks')
Rel(rg_aleksander, d_awh_appwm1_osdisk, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(dawhstorage, 'dawhstorage', 'Microsoft.Storage/storageAccounts')
Rel(rg_aleksander, dawhstorage, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(d_awhsandbox_kv, 'd-awhsandbox-kv', 'Microsoft.KeyVault/vaults')
Rel(rg_aleksander, d_awhsandbox_kv, 'Uses', 'Resource' )

AzureResourceGroups(rg_thomas, 'rg-thomas', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_thomas, 'Uses', 'Subscription' )

AzureResourceGroups(rg_sven, 'rg-sven', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_sven, 'Uses', 'Subscription' )

AzureResourceGroups(rg_tom, 'rg-tom', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_tom, 'Uses', 'Subscription' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(pgithubbackupstorage, 'pgithubbackupstorage', 'Microsoft.Storage/storageAccounts')
Rel(rg_tom, pgithubbackupstorage, 'Uses', 'Resource' )

!includeurl AzurePuml/Management/AzureAutomation.puml
AzureAutomation(GitHubBackupAutomation, 'GitHubBackupAutomation', 'Microsoft.Automation/automationAccounts')
Rel(rg_tom, GitHubBackupAutomation, 'Uses', 'Resource' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(test12345789, 'test12345789', 'Microsoft.KeyVault/vaults')
Rel(rg_tom, test12345789, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(dfrvgtbhnjmk, 'dfrvgtbhnjmk', 'Microsoft.Storage/storageAccounts')
Rel(rg_tom, dfrvgtbhnjmk, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(mediauploadtest, 'mediauploadtest', 'Microsoft.Storage/storageAccounts')
Rel(rg_tom, mediauploadtest, 'Uses', 'Resource' )

AzureResourceGroups(dna_test, 'dna-test', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, dna_test, 'Uses', 'Subscription' )

!includeurl AzurePuml/Security/AzureKeyVault.puml
AzureKeyVault(dna_test_kv_fhca, 'dna-test-kv-fhca', 'Microsoft.KeyVault/vaults')
Rel(dna_test, dna_test_kv_fhca, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureAvailabiltySet.puml
AzureAvailabiltySet(t_dna_rhel_avail, 't-dna-rhel-avail', 'Microsoft.Compute/availabilitySets')
Rel(dna_test, t_dna_rhel_avail, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(t_dna_rhel1_datadisk1, 't-dna-rhel1-datadisk1', 'Microsoft.Compute/disks')
Rel(dna_test, t_dna_rhel1_datadisk1, 'Uses', 'Resource' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(t_dna_rhel1_nic, 't-dna-rhel1-nic', 'Microsoft.Network/networkInterfaces')
Rel(dna_test, t_dna_rhel1_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(t_dna_rhel1, 't-dna-rhel1', 'Microsoft.Compute/virtualMachines')
Rel(dna_test, t_dna_rhel1, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(t_dna_rhel1_osdisk, 't-dna-rhel1-osdisk', 'Microsoft.Compute/disks')
Rel(dna_test, t_dna_rhel1_osdisk, 'Uses', 'Resource' )

AzureResourceGroups(rg_rolf, 'rg-rolf', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_rolf, 'Uses', 'Subscription' )

AzureResourceGroups(rg_siv, 'rg-siv', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_siv, 'Uses', 'Subscription' )

AzureResourceGroups(t_acs_sandbox, 't-acs-sandbox', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, t_acs_sandbox, 'Uses', 'Subscription' )

AzureResourceGroups(rg_audun_linux_test11, 'rg-audun-linux-test11', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_audun_linux_test11, 'Uses', 'Subscription' )

AzureResourceGroups(AzureBackupRG_norwayeast_1, 'AzureBackupRG_norwayeast_1', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, AzureBackupRG_norwayeast_1, 'Uses', 'Subscription' )

AzureResourceGroups(thomas_rg, 'thomas_rg', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, thomas_rg, 'Uses', 'Subscription' )

AzureResourceGroups(DefaultResourceGroup_null, 'DefaultResourceGroup-null', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, DefaultResourceGroup_null, 'Uses', 'Subscription' )

AzureResourceGroups(rbac_test, 'rbac-test', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rbac_test, 'Uses', 'Subscription' )

!includeurl AzurePuml/Networking/AzureNetworkInterface.puml
AzureNetworkInterface(t_linux_vm_nic, 't-linux-vm-nic', 'Microsoft.Network/networkInterfaces')
Rel(rbac_test, t_linux_vm_nic, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
AzureVirtualMachine(t_linux_vm, 't-linux-vm', 'Microsoft.Compute/virtualMachines')
Rel(rbac_test, t_linux_vm, 'Uses', 'Resource' )

!includeurl AzurePuml/Compute/AzureDisk.puml
AzureDisk(t_linux_vm_osdisk, 't-linux-vm-osdisk', 'Microsoft.Compute/disks')
Rel(rbac_test, t_linux_vm_osdisk, 'Uses', 'Resource' )

AzureResourceGroups(maksym_finops, 'maksym-finops', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, maksym_finops, 'Uses', 'Subscription' )

!includeurl AzurePuml/Databases/AzureDataFactory.puml
AzureDataFactory(MyHubPublic_engine_tj5eravonizvq, 'MyHubPublic-engine-tj5eravonizvq', 'Microsoft.DataFactory/factories')
Rel(maksym_finops, MyHubPublic_engine_tj5eravonizvq, 'Uses', 'Resource' )

!includeurl AzurePuml/Identity/AzureManagedIdentity.puml
AzureManagedIdentity(myhubpublictj5eravonizvq_blobManager, 'myhubpublictj5eravonizvq_blobManager', 'Microsoft.ManagedIdentity/userAssignedIdentities')
Rel(maksym_finops, myhubpublictj5eravonizvq_blobManager, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(myhubpublictj5eravonizvq, 'myhubpublictj5eravonizvq', 'Microsoft.Storage/storageAccounts')
Rel(maksym_finops, myhubpublictj5eravonizvq, 'Uses', 'Resource' )

!includeurl AzurePuml/Identity/AzureManagedIdentity.puml
AzureManagedIdentity(MyHubPublic_engine_tj5eravonizvq_triggerManager, 'MyHubPublic-engine-tj5eravonizvq_triggerManager', 'Microsoft.ManagedIdentity/userAssignedIdentities')
Rel(maksym_finops, MyHubPublic_engine_tj5eravonizvq_triggerManager, 'Uses', 'Resource' )

!includeurl AzurePuml/Integration/AzureSystemTopic.puml
AzureSystemTopic(myhubpublictj5eravonizvq_a0d0457d_f302_4876_ae91_5bc42dbd3223, 'myhubpublictj5eravonizvq-a0d0457d-f302-4876-ae91-5bc42dbd3223', 'Microsoft.EventGrid/systemTopics')
Rel(maksym_finops, myhubpublictj5eravonizvq_a0d0457d_f302_4876_ae91_5bc42dbd3223, 'Uses', 'Resource' )

AzureResourceGroups(maksym_maintenanceConfig, 'maksym-maintenanceConfig', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, maksym_maintenanceConfig, 'Uses', 'Subscription' )

!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
AzureVirtualNetwork(maksym_maintenanceconfig_vnet, 'maksym-maintenanceconfig-vnet', 'Microsoft.Network/virtualNetworks')
Rel(maksym_maintenanceConfig, maksym_maintenanceconfig_vnet, 'Uses', 'Resource' )

AzureResourceGroups(cloud_shell_storage_westeurope, 'cloud-shell-storage-westeurope', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, cloud_shell_storage_westeurope, 'Uses', 'Subscription' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(csb100320041428ff8f, 'csb100320041428ff8f', 'Microsoft.Storage/storageAccounts')
Rel(cloud_shell_storage_westeurope, csb100320041428ff8f, 'Uses', 'Resource' )

!includeurl AzurePuml/Storage/AzureStorage.puml
AzureStorage(csb1003200033b9b8b7, 'csb1003200033b9b8b7', 'Microsoft.Storage/storageAccounts')
Rel(cloud_shell_storage_westeurope, csb1003200033b9b8b7, 'Uses', 'Resource' )

LAYOUT_WITH_LEGEND()
@enduml
