@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "2": {
    "provisioningState": "Succeeded",
    "type": "AzureDiskEncryption",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "2.2",
    "publisher": "Microsoft.Azure.Security",
    "settings": {
      "EncryptionOperation": "EnableEncryption",
      "KeyVaultResourceId": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb",
      "KeyVaultURL": "https://vm-mf-kv-gssb.vault.azure.net/",
      "VolumeType": "All",
      "KeyEncryptionAlgorithm": "RSA-OAEP",
      "KeyEncryptionKeyURL": "https://vm-mf-kv-gssb.vault.azure.net/keys/lz-vm-disk-encrypt-key/025cf7e5becf47c78c90657676398878",
      "KekVaultResourceId": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb"
    }
  },
  "1": {
    "provisioningState": "Succeeded",
    "type": "AzureDiskEncryption",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "2.2",
    "publisher": "Microsoft.Azure.Security",
    "settings": {
      "EncryptionOperation": "EnableEncryption",
      "KeyVaultResourceId": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb",
      "KeyVaultURL": "https://vm-mf-kv-gssb.vault.azure.net/",
      "VolumeType": "All",
      "KeyEncryptionAlgorithm": "RSA-OAEP",
      "KeyEncryptionKeyURL": "https://vm-mf-kv-gssb.vault.azure.net/keys/lz-vm-disk-encrypt-key/025cf7e5becf47c78c90657676398878",
      "KekVaultResourceId": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb"
    }
  },
  "4": {
    "provisioningState": "Succeeded",
    "type": "AzureDiskEncryption",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "2.2",
    "publisher": "Microsoft.Azure.Security",
    "settings": {
      "EncryptionOperation": "EnableEncryption",
      "KeyVaultResourceId": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb",
      "KeyVaultURL": "https://vm-mf-kv-gssb.vault.azure.net/",
      "VolumeType": "All",
      "KeyEncryptionAlgorithm": "RSA-OAEP",
      "KeyEncryptionKeyURL": "https://vm-mf-kv-gssb.vault.azure.net/keys/lz-vm-disk-encrypt-key/025cf7e5becf47c78c90657676398878",
      "KekVaultResourceId": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb"
    }
  },
  "0": {
    "provisioningState": "Succeeded",
    "type": "AzureDiskEncryption",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "2.2",
    "publisher": "Microsoft.Azure.Security",
    "settings": {
      "EncryptionOperation": "EnableEncryption",
      "KeyVaultResourceId": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb",
      "KeyVaultURL": "https://vm-mf-kv-gssb.vault.azure.net/",
      "VolumeType": "All",
      "KeyEncryptionAlgorithm": "RSA-OAEP",
      "KeyEncryptionKeyURL": "https://vm-mf-kv-gssb.vault.azure.net/keys/lz-vm-disk-encrypt-key/025cf7e5becf47c78c90657676398878",
      "KekVaultResourceId": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb"
    }
  },
  "3": {
    "provisioningState": "Succeeded",
    "type": "AzureDiskEncryption",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "2.2",
    "publisher": "Microsoft.Azure.Security",
    "settings": {
      "EncryptionOperation": "EnableEncryption",
      "KeyVaultResourceId": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb",
      "KeyVaultURL": "https://vm-mf-kv-gssb.vault.azure.net/",
      "VolumeType": "All",
      "KeyEncryptionAlgorithm": "RSA-OAEP",
      "KeyEncryptionKeyURL": "https://vm-mf-kv-gssb.vault.azure.net/keys/lz-vm-disk-encrypt-key/025cf7e5becf47c78c90657676398878",
      "KekVaultResourceId": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb"
    }
  }
}
}
@enduml
