@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "platformFaultDomainCount": 2,
  "virtualMachineScaleSetMigrationInfo": {
    "defaultVirtualMachineScaleSetInfo": {
      "constrainedMaximumCapacity": true,
      "defaultVirtualMachineScaleSet": {
        "id": "/subscriptions/0/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.Compute/virtualMachineScaleSets/vm-mf-avail"
      }
    }
  },
  "platformUpdateDomainCount": 5,
  "virtualMachines": [
    {
      "id": "/subscriptions/0/resourceGroups/MAKSYM-MAINTENANCECONFIG/providers/Microsoft.Compute/virtualMachines/VM-MF1"
    },
    {
      "id": "/subscriptions/0/resourceGroups/MAKSYM-MAINTENANCECONFIG/providers/Microsoft.Compute/virtualMachines/VM-MF2"
    }
  ]
}
}
@enduml
