@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "publicNetworkAccess": "Enabled",
  "networkAccessPolicy": "AllowAll",
  "timeCreated": "2025-06-11T13:50:05.7495737Z",
  "diskSizeGB": 200,
  "encryption": {
    "type": "EncryptionAtRestWithPlatformKey"
  },
  "diskSizeBytes": 214748364800,
  "creationData": {
    "createOption": "Empty"
  },
  "LastOwnershipUpdateTime": "2025-06-11T13:50:28.1258567Z",
  "diskState": "Attached",
  "uniqueId": "3c96c986-fa2c-4721-a40a-737bcca0ea37",
  "diskMBpsReadWrite": 125,
  "diskIOPSReadWrite": 1100,
  "tier": "P15"
}
}
@enduml
