@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "publicNetworkAccess": "Enabled",
  "networkAccessPolicy": "AllowAll",
  "diskSizeGB": 200,
  "timeCreated": "2025-06-11T13:50:05.4527653Z",
  "encryption": {
    "type": "EncryptionAtRestWithPlatformKey"
  },
  "diskSizeBytes": 214748364800,
  "creationData": {
    "createOption": "Empty"
  },
  "LastOwnershipUpdateTime": "2025-06-11T13:50:28.1101652Z",
  "diskState": "Attached",
  "uniqueId": "27cbc378-56ff-4e5b-a911-4263f1a7e80b",
  "diskIOPSReadWrite": 1100,
  "diskMBpsReadWrite": 125,
  "tier": "P15"
}
}
@enduml
