@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "publicNetworkAccess": "Enabled",
  "networkAccessPolicy": "AllowAll",
  "diskSizeGB": 128,
  "timeCreated": "2025-06-11T13:50:28.11Z",
  "hyperVGeneration": "V1",
  "diskSizeBytes": 137438953472,
  "supportedCapabilities": {
    "architecture": "x64",
    "acceleratedNetwork": true,
    "diskControllerTypes": "SCSI"
  },
  "encryption": {
    "type": "EncryptionAtRestWithPlatformKey"
  },
  "creationData": {
    "createOption": "FromImage",
    "imageReference": {
      "id": "/Subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/Providers/Microsoft.Compute/Locations/NorwayEast/Publishers/MicrosoftWindowsServer/ArtifactTypes/VMImage/Offers/WindowsServer/Skus/2022-Datacenter/Versions/20348.3807.250605"
    }
  },
  "LastOwnershipUpdateTime": "2025-06-11T13:50:28.125Z",
  "diskState": "Attached",
  "diskIOPSReadWrite": 500,
  "diskMBpsReadWrite": 100,
  "uniqueId": "3ce9e81d-a964-4fcd-95fb-d0e89816f97a",
  "osType": "Windows",
  "supportsHibernation": true,
  "tier": "P10",
  "encryptionSettingsCollection": {
    "enabled": true,
    "encryptionSettings": [
      {
        "diskEncryptionKey": {
          "sourceVault": {
            "id": "/subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb"
          },
          "secretUrl": "https://vm-mf-kv-gssb.vault.azure.net/secrets/5A22E389-89B6-4DD7-8566-17668EB29D3D/941fe111afec49ab8a24bd4ef3cfc8ad"
        },
        "keyEncryptionKey": {
          "sourceVault": {
            "id": "/subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/resourceGroups/maksym-maintenanceConfig/providers/Microsoft.KeyVault/vaults/vm-mf-kv-gssb"
          },
          "keyUrl": "https://vm-mf-kv-gssb.vault.azure.net/keys/lz-vm-disk-encrypt-key/025cf7e5becf47c78c90657676398878"
        }
      }
    ],
    "encryptionSettingsVersion": "1.1"
  }
}
}
@enduml
