@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "type": "AdminCenter",
  "autoUpgradeMinorVersion": true,
  "typeHandlerVersion": "0.0",
  "enableAutomaticUpgrade": true,
  "publisher": "Microsoft.AdminCenter",
  "settings": {
    "port": "6516",
    "salt": "0000060472051858564455601300551900087"
  }
}
}
@enduml
