@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties [
  {
    "provisioningState": "Succeeded",
    "type": "BGInfo",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "2.1",
    "publisher": "Microsoft.Compute"
  },
  {
    "provisioningState": "Succeeded",
    "type": "BGInfo",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "2.1",
    "publisher": "Microsoft.Compute"
  },
  {
    "provisioningState": "Succeeded",
    "type": "BGInfo",
    "autoUpgradeMinorVersion": true,
    "typeHandlerVersion": "2.1",
    "publisher": "Microsoft.Compute"
  }
]
}
@enduml
