@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "idleTimeoutInMinutes": 15,
  "resourceGuid": "2f01cec8-92d6-482d-9325-f5a28567e6e4",
  "publicIPAllocationMethod": "Static",
  "publicIPAddressVersion": "IPv4",
  "ipAddress": "20.251.200.196",
  "ipConfiguration": {
    "id": "/subscriptions/996465bb-34d8-4c7d-99c1-bab3805301c8/resourceGroups/rg-bjornjorgen/providers/Microsoft.Network/networkInterfaces/vnet-norwayeast-nic01-28e3bab2/ipConfigurations/vnet-norwayeast-nic01-defaultIpConfiguration"
  },
  "ipTags": []
}
}
@enduml
