@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "platformFaultDomainCount": 2,
  "virtualMachineScaleSetMigrationInfo": {
    "defaultVirtualMachineScaleSetInfo": {
      "defaultVirtualMachineScaleSet": {
        "id": "/subscriptions/0/resourceGroups/rg-bjornjorgen/providers/Microsoft.Compute/virtualMachineScaleSets/t-bjs2-win-avail"
      },
      "constrainedMaximumCapacity": true
    }
  },
  "platformUpdateDomainCount": 5,
  "virtualMachines": [
    {
      "id": "/subscriptions/0/resourceGroups/RG-BJORNJORGEN/providers/Microsoft.Compute/virtualMachines/T-BJS2-WIN1"
    }
  ]
}
}
@enduml
