@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "ipConfigurations": [
    {
      "properties": {
        "provisioningState": "Succeeded",
        "privateIPAllocationMethod": "Dynamic",
        "subnet": {
          "id": "/subscriptions/0/resourceGroups/lz-network-norwayeast/providers/Microsoft.Network/virtualNetworks/lz-network-norwayeast-vnet/subnets/AzureBastionSubnet"
        },
        "publicIPAddress": {
          "id": "/subscriptions/0/resourceGroups/lz-network-norwayeast/providers/Microsoft.Network/publicIPAddresses/lz-network-norwayeast-vnet-ip"
        }
      },
      "name": "IpConf",
      "type": "Microsoft.Network/bastionHosts/bastionHostIpConfigurations",
      "id": "/subscriptions/0/resourceGroups/lz-network-norwayeast/providers/Microsoft.Network/bastionHosts/lz-network-norwayeast-vnet-bastion/bastionHostIpConfigurations/IpConf",
      "etag": "W/\"a5fe6cd5-075b-48ad-92ba-acf0c979057a\""
    }
  ],
  "scaleUnits": 2,
  "enableTunneling": true,
  "enableShareableLink": false,
  "enableIpConnect": false,
  "disableCopyPaste": false,
  "dnsName": "bst-16eafad2-44a4-40c0-80b0-80e3693868c6.bastion.azure.com",
  "enableKerberos": false,
  "enablePrivateOnlyBastion": false,
  "enableSessionRecording": false,
  "publicUri": "/subscriptions/0/resourceGroups/lz-network-norwayeast/providers/Microsoft.Network/publicIPAddresses/lz-network-norwayeast-vnet-ip"
}
}
@enduml
