@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "0": {
    "provisioningState": "Succeeded",
    "publicNetworkAccess": "Enabled",
    "networkAccessPolicy": "AllowAll",
    "diskSizeGB": 30,
    "timeCreated": "2025-04-03T08:13:51.8852745Z",
    "hyperVGeneration": "V1",
    "encryption": {
      "type": "EncryptionAtRestWithPlatformKey"
    },
    "diskSizeBytes": 32213303296,
    "creationData": {
      "createOption": "FromImage",
      "imageReference": {
        "id": "/Subscriptions/94460934-16ae-42df-af06-1cf4f1a6bb7c/Providers/Microsoft.Compute/Locations/NorwayEast/Publishers/canonical/ArtifactTypes/VMImage/Offers/0001-com-ubuntu-server-jammy/Skus/22_04-lts/Versions/22.04.202503240"
      }
    },
    "LastOwnershipUpdateTime": "2025-04-03T08:13:51.8852745Z",
    "diskState": "Attached",
    "supportedCapabilities": {
      "architecture": "x64",
      "acceleratedNetwork": true,
      "diskControllerTypes": "SCSI, NVMe"
    },
    "uniqueId": "f979c197-47eb-403e-a980-97272193df3c",
    "diskIOPSReadWrite": 500,
    "diskMBpsReadWrite": 60,
    "osType": "Linux",
    "supportsHibernation": true
  },
  "1": {
    "provisioningState": "Succeeded",
    "publicNetworkAccess": "Enabled",
    "networkAccessPolicy": "AllowAll",
    "diskSizeGB": 30,
    "timeCreated": "2025-04-03T08:13:51.8852745Z",
    "hyperVGeneration": "V1",
    "encryption": {
      "type": "EncryptionAtRestWithPlatformKey"
    },
    "diskSizeBytes": 32213303296,
    "creationData": {
      "createOption": "FromImage",
      "imageReference": {
        "id": "/Subscriptions/94460934-16ae-42df-af06-1cf4f1a6bb7c/Providers/Microsoft.Compute/Locations/NorwayEast/Publishers/canonical/ArtifactTypes/VMImage/Offers/0001-com-ubuntu-server-jammy/Skus/22_04-lts/Versions/22.04.202503240"
      }
    },
    "LastOwnershipUpdateTime": "2025-04-03T08:13:51.8852745Z",
    "diskState": "Attached",
    "supportedCapabilities": {
      "architecture": "x64",
      "acceleratedNetwork": true,
      "diskControllerTypes": "SCSI, NVMe"
    },
    "uniqueId": "f979c197-47eb-403e-a980-97272193df3c",
    "diskIOPSReadWrite": 500,
    "diskMBpsReadWrite": 60,
    "osType": "Linux",
    "supportsHibernation": true
  }
}
}
@enduml
