@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "0": {
    "provisioningState": "Succeeded",
    "enableAcceleratedNetworking": false,
    "resourceGuid": "f6dd2278-f10e-4317-8069-ce5a3f2226c2",
    "disableTcpStateTracking": false,
    "defaultOutboundConnectivityEnabled": true,
    "vnetEncryptionSupported": false,
    "ipConfigurations": [
      {
        "properties": {
          "provisioningState": "Succeeded",
          "privateIPAddressVersion": "IPv4",
          "privateIPAllocationMethod": "Dynamic",
          "privateIPAddress": "10.0.0.11",
          "primary": true,
          "subnet": {
            "id": "/subscriptions/0/resourceGroups/lz-network-norwayeast/providers/Microsoft.Network/virtualNetworks/lz-network-norwayeast-vnet/subnets/dna-test-1"
          }
        },
        "name": "ipconfig1",
        "type": "Microsoft.Network/networkInterfaces/ipConfigurations",
        "id": "/subscriptions/0/resourceGroups/rbac-test/providers/Microsoft.Network/networkInterfaces/t-linux-vm-nic/ipConfigurations/ipconfig1",
        "etag": "W/\"771555a8-4160-4375-84d9-7d9936cb7026\""
      }
    ],
    "enableIPForwarding": false,
    "primary": true,
    "tapConfigurations": [],
    "hostedWorkloads": [],
    "allowPort25Out": true,
    "auxiliaryMode": "None",
    "dnsSettings": {
      "appliedDnsServers": [],
      "internalDomainNameSuffix": "pquq0qan4vse5gqto15kewgzsd.oslx.internal.cloudapp.net",
      "dnsServers": []
    },
    "macAddress": "00-22-48-DC-F5-F0",
    "auxiliarySku": "None",
    "virtualMachine": {
      "id": "/subscriptions/0/resourceGroups/rbac-test/providers/Microsoft.Compute/virtualMachines/t-linux-vm"
    },
    "nicType": "Standard"
  },
  "1": {
    "provisioningState": "Succeeded",
    "enableAcceleratedNetworking": false,
    "resourceGuid": "f6dd2278-f10e-4317-8069-ce5a3f2226c2",
    "disableTcpStateTracking": false,
    "defaultOutboundConnectivityEnabled": true,
    "vnetEncryptionSupported": false,
    "ipConfigurations": [
      {
        "properties": {
          "provisioningState": "Succeeded",
          "privateIPAddressVersion": "IPv4",
          "privateIPAllocationMethod": "Dynamic",
          "privateIPAddress": "10.0.0.11",
          "primary": true,
          "subnet": {
            "id": "/subscriptions/0/resourceGroups/lz-network-norwayeast/providers/Microsoft.Network/virtualNetworks/lz-network-norwayeast-vnet/subnets/dna-test-1"
          }
        },
        "name": "ipconfig1",
        "type": "Microsoft.Network/networkInterfaces/ipConfigurations",
        "id": "/subscriptions/0/resourceGroups/rbac-test/providers/Microsoft.Network/networkInterfaces/t-linux-vm-nic/ipConfigurations/ipconfig1",
        "etag": "W/\"771555a8-4160-4375-84d9-7d9936cb7026\""
      }
    ],
    "enableIPForwarding": false,
    "primary": true,
    "tapConfigurations": [],
    "hostedWorkloads": [],
    "allowPort25Out": true,
    "auxiliaryMode": "None",
    "dnsSettings": {
      "appliedDnsServers": [],
      "internalDomainNameSuffix": "pquq0qan4vse5gqto15kewgzsd.oslx.internal.cloudapp.net",
      "dnsServers": []
    },
    "macAddress": "00-22-48-DC-F5-F0",
    "auxiliarySku": "None",
    "virtualMachine": {
      "id": "/subscriptions/0/resourceGroups/rbac-test/providers/Microsoft.Compute/virtualMachines/t-linux-vm"
    },
    "nicType": "Standard"
  }
}
}
@enduml
