@startuml
!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Management/AzureSubscription.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml

AzureSubscription(KLP_LZ_SRE_playground_Sandbox, 'KLP LZ SRE playground Sandbox', 'Azure Landing Zone')
AzureResourceGroups(lz_norwayeast, 'lz-norwayeast', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, lz_norwayeast, 'Uses', 'Subscription' )

AzureResourceGroups(NetworkWatcherRG, 'NetworkWatcherRG', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, NetworkWatcherRG, 'Uses', 'Subscription' )

AzureResourceGroups(rg_email, 'rg-email', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_email, 'Uses', 'Subscription' )

AzureResourceGroups(lz_network_norwayeast, 'lz-network-norwayeast', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, lz_network_norwayeast, 'Uses', 'Subscription' )

AzureResourceGroups(linux_test, 'linux-test', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, linux_test, 'Uses', 'Subscription' )

AzureResourceGroups(rg_audun, 'rg-audun', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_audun, 'Uses', 'Subscription' )

AzureResourceGroups(rg_bjornjorgen, 'rg-bjornjorgen', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_bjornjorgen, 'Uses', 'Subscription' )

AzureResourceGroups(rg_daniel, 'rg-daniel', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_daniel, 'Uses', 'Subscription' )

AzureResourceGroups(rg_aleksander, 'rg-aleksander', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_aleksander, 'Uses', 'Subscription' )

AzureResourceGroups(rg_thomas, 'rg-thomas', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_thomas, 'Uses', 'Subscription' )

AzureResourceGroups(rg_sven, 'rg-sven', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_sven, 'Uses', 'Subscription' )

AzureResourceGroups(rg_tom, 'rg-tom', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_tom, 'Uses', 'Subscription' )

AzureResourceGroups(dna_test, 'dna-test', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, dna_test, 'Uses', 'Subscription' )

AzureResourceGroups(rg_rolf, 'rg-rolf', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_rolf, 'Uses', 'Subscription' )

AzureResourceGroups(rg_siv, 'rg-siv', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_siv, 'Uses', 'Subscription' )

AzureResourceGroups(t_acs_sandbox, 't-acs-sandbox', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, t_acs_sandbox, 'Uses', 'Subscription' )

AzureResourceGroups(rg_audun_linux_test11, 'rg-audun-linux-test11', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rg_audun_linux_test11, 'Uses', 'Subscription' )

AzureResourceGroups(AzureBackupRG_norwayeast_1, 'AzureBackupRG_norwayeast_1', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, AzureBackupRG_norwayeast_1, 'Uses', 'Subscription' )

AzureResourceGroups(thomas_rg, 'thomas_rg', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, thomas_rg, 'Uses', 'Subscription' )

AzureResourceGroups(DefaultResourceGroup_null, 'DefaultResourceGroup-null', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, DefaultResourceGroup_null, 'Uses', 'Subscription' )

AzureResourceGroups(rbac_test, 'rbac-test', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, rbac_test, 'Uses', 'Subscription' )

AzureResourceGroups(maksym_finops, 'maksym-finops', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, maksym_finops, 'Uses', 'Subscription' )

AzureResourceGroups(maksym_maintenanceConfig, 'maksym-maintenanceConfig', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, maksym_maintenanceConfig, 'Uses', 'Subscription' )

AzureResourceGroups(cloud_shell_storage_westeurope, 'cloud-shell-storage-westeurope', 'Azure Resource Group')
Rel(KLP_LZ_SRE_playground_Sandbox, cloud_shell_storage_westeurope, 'Uses', 'Subscription' )

LAYOUT_WITH_LEGEND()
@enduml
