@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Updating",
  "type": "VMAccessForLinux",
  "autoUpgradeMinorVersion": true,
  "typeHandlerVersion": "1.5",
  "publisher": "Microsoft.OSTCExtensions"
}
}
@enduml
