@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "0": {
    "provisioningState": "Succeeded",
    "timeCreated": "2024-09-16T09:09:22.4649863Z",
    "storageProfile": {
      "imageReference": {
        "publisher": "Canonical",
        "version": "latest",
        "exactVersion": "22.04.202409130",
        "sku": "22_04-lts",
        "offer": "0001-com-ubuntu-server-jammy"
      },
      "dataDisks": [],
      "osDisk": {
        "name": "t-linux-vm-osdisk",
        "createOption": "FromImage",
        "deleteOption": "Delete",
        "managedDisk": {
          "id": "/subscriptions/0/resourceGroups/LINUX-TEST/providers/Microsoft.Compute/disks/t-linux-vm-osdisk"
        },
        "osType": "Linux",
        "caching": "ReadWrite"
      }
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "properties": {
            "deleteOption": "Delete"
          },
          "id": "/subscriptions/0/resourceGroups/linux-test/providers/Microsoft.Network/networkInterfaces/t-linux-vm-nic"
        }
      ]
    },
    "hardwareProfile": {
      "vmSize": "Standard_A1_v2"
    },
    "osProfile": {
      "requireGuestProvisionSignal": true,
      "computerName": "t-linux-vm",
      "allowExtensionOperations": true,
      "adminUsername": "sysadm",
      "secrets": [],
      "linuxConfiguration": {
        "provisionVMAgent": true,
        "disablePasswordAuthentication": false,
        "patchSettings": {
          "assessmentMode": "ImageDefault",
          "patchMode": "ImageDefault"
        }
      }
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true
      }
    },
    "extended": {
      "instanceView": {
        "hyperVGeneration": "V1",
        "powerState": {
          "displayStatus": "VM deallocated",
          "level": "Info",
          "code": "PowerState/deallocated"
        }
      }
    },
    "vmId": "939bbefa-119d-4a93-b521-a639deb2d088"
  },
  "1": {
    "provisioningState": "Succeeded",
    "timeCreated": "2024-09-16T09:09:22.4649863Z",
    "storageProfile": {
      "imageReference": {
        "publisher": "Canonical",
        "version": "latest",
        "exactVersion": "22.04.202409130",
        "sku": "22_04-lts",
        "offer": "0001-com-ubuntu-server-jammy"
      },
      "dataDisks": [],
      "osDisk": {
        "name": "t-linux-vm-osdisk",
        "createOption": "FromImage",
        "deleteOption": "Delete",
        "managedDisk": {
          "id": "/subscriptions/0/resourceGroups/LINUX-TEST/providers/Microsoft.Compute/disks/t-linux-vm-osdisk"
        },
        "osType": "Linux",
        "caching": "ReadWrite"
      }
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "properties": {
            "deleteOption": "Delete"
          },
          "id": "/subscriptions/0/resourceGroups/linux-test/providers/Microsoft.Network/networkInterfaces/t-linux-vm-nic"
        }
      ]
    },
    "hardwareProfile": {
      "vmSize": "Standard_A1_v2"
    },
    "osProfile": {
      "requireGuestProvisionSignal": true,
      "computerName": "t-linux-vm",
      "allowExtensionOperations": true,
      "adminUsername": "sysadm",
      "secrets": [],
      "linuxConfiguration": {
        "provisionVMAgent": true,
        "disablePasswordAuthentication": false,
        "patchSettings": {
          "assessmentMode": "ImageDefault",
          "patchMode": "ImageDefault"
        }
      }
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true
      }
    },
    "extended": {
      "instanceView": {
        "hyperVGeneration": "V1",
        "powerState": {
          "displayStatus": "VM deallocated",
          "level": "Info",
          "code": "PowerState/deallocated"
        }
      }
    },
    "vmId": "939bbefa-119d-4a93-b521-a639deb2d088"
  }
}
}
@enduml
