@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "encryption": {
    "keySource": "Microsoft.Automation",
    "identity": {
      "userAssignedIdentity": null
    }
  },
  "privateEndpointConnections": [],
  "creationTime": "2025-02-05T07:40:00.93Z",
  "state": "Ok",
  "sku": {
    "name": "Basic",
    "capacity": null,
    "family": null
  },
  "disableLocalAuth": false,
  "lastModifiedTime": "2025-02-19T08:20:50.0533333Z",
  "lastModifiedBy": null,
  "automationHybridServiceUrl": "https://8303b635-e1a6-4db3-9026-d345e5acad5e.jrds.noe.azure-automation.net/automationAccounts/8303b635-e1a6-4db3-9026-d345e5acad5e",
  "RuntimeConfiguration": {
    "powershell72": {
      "builtinModules": {
        "Az": "11.2.0"
      }
    },
    "powershell7": {
      "builtinModules": {
        "Az": "8.0.0"
      }
    },
    "powershell": {
      "builtinModules": {
        "Az": "11.2.0"
      }
    }
  },
  "RegistrationUrl": "https://8303b635-e1a6-4db3-9026-d345e5acad5e.agentsvc.noe.azure-automation.net/accounts/8303b635-e1a6-4db3-9026-d345e5acad5e"
}
}
@enduml
