@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "publicNetworkAccess": "Enabled",
  "encryption": {
    "keySource": "Microsoft.Storage",
    "services": {
      "blob": {
        "enabled": true,
        "lastEnabledTime": "2025-02-05T07:36:57.0284319Z",
        "keyType": "Account"
      },
      "file": {
        "enabled": true,
        "lastEnabledTime": "2025-02-05T07:36:57.0284319Z",
        "keyType": "Account"
      }
    }
  },
  "privateEndpointConnections": [],
  "supportsHttpsTrafficOnly": true,
  "allowBlobPublicAccess": false,
  "minimumTlsVersion": "TLS1_2",
  "allowCrossTenantReplication": false,
  "primaryEndpoints": {
    "blob": "https://pgithubbackupstorage.blob.core.windows.net/",
    "file": "https://pgithubbackupstorage.file.core.windows.net/",
    "table": "https://pgithubbackupstorage.table.core.windows.net/",
    "queue": "https://pgithubbackupstorage.queue.core.windows.net/",
    "web": "https://pgithubbackupstorage.z1.web.core.windows.net/",
    "dfs": "https://pgithubbackupstorage.dfs.core.windows.net/"
  },
  "keyCreationTime": {
    "key2": "2025-02-05T07:36:57.0128319Z",
    "key1": "2025-02-05T07:36:57.0128319Z"
  },
  "statusOfPrimary": "available",
  "primaryLocation": "norwayeast",
  "creationTime": "2025-02-05T07:36:56.9502528Z",
  "networkAcls": {
    "virtualNetworkRules": [],
    "defaultAction": "Allow",
    "ipv6Rules": [],
    "ipRules": [],
    "bypass": "AzureServices",
    "resourceAccessRules": []
  },
  "allowSharedKeyAccess": true,
  "accessTier": "Cool",
  "defaultToOAuthAuthentication": false
}
}
@enduml
