@startuml

title Resources Display - Component Diagram

component Component {

json  Resource_Properties {
  "provisioningState": "Succeeded",
  "publicNetworkAccess": "Enabled",
  "networkAcls": {
    "virtualNetworkRules": [],
    "defaultAction": "Allow",
    "ipRules": [],
    "bypass": "None"
  },
  "tenantId": "67508d80-2b69-484e-ab62-ab263ca94733",
  "enabledForTemplateDeployment": false,
  "sku": {
    "name": "Standard",
    "family": "A"
  },
  "enabledForDeployment": false,
  "enabledForDiskEncryption": false,
  "softDeleteRetentionInDays": 90,
  "enableRbacAuthorization": true,
  "accessPolicies": [],
  "enableSoftDelete": true,
  "vaultUri": "https://test12345789.vault.azure.net/"
}
}
@enduml
